submariner-io/submariner

- pkg/util/util.go
- tokenChars is not used - remove it
- In GetClusterCRDName, it uses Sprintf with format "%s" but cluster.Spec.ClusterID
is already a string - no need to use Sprintf.
> Fix minor issues in util

- pkg/routeagent/controllers/route/route.go
There are 2 calls to Errorf where the format string contains
a specifier but doesn't pass a format arg. Pass in the appropriate
arg.
> Fix incorrect Errorf formatting

- README.md
Normally in a vanilla kubernetes deployment, there is a single endpoint for kubernetes as shown below.
[centos@eosmaster ~]$ kubectl -n default get endpoints kubernetes -o json
<SNIP>
"ports": [
{
"name": "https",
"port": 6443,
"protocol": "TCP"
}
]
However, in some deployments (like OpenShift), there could be multiple endpoints.
[centos@wosmaster ~]$ oc -n default get endpoints kubernetes -o json
<SNIP>
"ports": [
{
"name": "dns",
"port": 8053,
"protocol": "UDP"
},
{
"name": "https",
"port": 8443,
"protocol": "TCP"
},
{
"name": "dns-tcp",
"port": 8053,
"protocol": "TCP"
}
]
This patch updates the SUBMARINER_BROKER_URL to use the appropriate "https" endpoint.
> Update SUBMARINER_BROKER_URL to use https endpoint

- README.md
The installation steps are updated to include the configurations required for granting the service account the appropriate security context constraints.
While deploying Submariner in Openshift on the Data nodes, it is seen that Submariner and Submariner-routeagent DaemonSet pods move to error state due to security context constraints.
Error:
oc describe ds submariner-routeagent
<SNIP>
---- ------ ---- ---- -------
Warning FailedCreate 2m (x65 over 4h) daemonset-controller Error creating: pods "submariner-routeagent-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged …
> Update the installation steps

- .travis.yml
Add initial support for travisci. Allow external contributors to perform dapper build, based on existing scripts in travisci.
> Add initial support for travisci

- pkg/cableengine/ipsec/ipsec.go
There are several funtions that obtain a ClientConn via getClient
locally which leads to multiple ClientConn instances created and
closed in a call chain. Optimize by creating a single ClientConn and
passing to the lower-level functions.
> Reuse ClientConn in ipsec

- pkg/datastore/kubernetes/kubernetes.go
- There were several call sites that did not check the error return value.
Either propagate the error or at least log it.
- There were several calls to panic in cases where an update operation failed.
It seems a bit harsh to terminate in this case and is inconsistent with the
handling of other failed CRUD operations (which previously ignored errors).
For consistency, CRUD failures now return and propagate the error.
- Added format args to some log messages to provide more context
- Modified the wording in some log messages for consistency
> Improve error handling/reporting in kubernetes.go

- main.go
When exiting from main() because of a configuration error, the stack
traces aren’t useful and would only confuse users. This patch uses
Exitf() instead of Fatalf(), which still exits, but with code 1
instead of 255, and no stack trace.
> Stop printing stack traces on some fatal errors

- pkg/cableengine/ipsec/ipsec.go
OpenShift SDN programs pipeline as follows.
1. For the traffic that is destined to the Cluster network
(i.e., destination IP is a POD/Service IP and is not on the same node),
it steers the traffic over the VxLAN tunnels that are configured between
the Nodes in the Cluster.
2. For non-cluster traffic, OVS pipeline steers the traffic over the tun0
interface and then over the physical interface and finally to the default
Gateway configured on the Node.
When we install Submariner with OpenShift 3.11 (ovs-subnet SDN) and
try to ping from POD1 on West Cluster to POD2 (on non-Gateway Node)
of East Cluster, the sourceIP of the traffic seen on POD2 will be the
GatewayNodeIpOfWestCluster.
So, the return traffic from the POD was going over the tun0 interface to the
default-gw configured on the Node …
> Fix inter cluster POD to POD(non-Gw) connectivity issue

- pkg/routeagent/controllers/route/route.go
- pkg/routeagent/main.go
- Renamed package from routecontroller to route as controller is already in
the import path and makes it consistent with tunnel.go
- route.RouteController -> route.Controller
- route.NewRouteController -> route.NewController
> Refactor route controller to avoid stuttering

- scripts/kind-e2e/e2e.sh
This adds a -k option to keep the clusters running after an e2e run,
and the complementary -c option to destroy the clusters.
> Provide control over e2e cleanup

- scripts/validate
Currently golint and gofmt are used in shadow mode.
I would like to propose to use golangci-lint.
golangci-lint is a linters aggregator. Has number of advantages:
1. It's 5 times faster than gometalinter. 
2. It's easy to integrate and use, has nice output and has a minimum number of false positives. 
3. It supports go modules.
4. Long list of supported linters. https://github.com/golangci/golangci-lint#supported-linters
5. Good IDE integration support. https://github.com/golangci/golangci-lint#editor-integration
This PR will change the **make validate** command to run golangci-lint on demand. 
Test locally with **make validate** command.
> Enable golangci-lint support

- scripts/validate
This will ensure our formatting stays consistent (once we run
scripts/validate...).
> Add goimports to scripts/validate

- scripts/test
test/e2e directory is being found by the test script, and
it will fail when go test tries to run it. This stops
test/e2e being found out by the discovery script.
> Fix make test after E2E being merged

- Makefile
The presence of the test directory broke this.
> Add test as a phony target to restore "make test"

- main.go
- pkg/cableengine/ipsec/ipsec.go
- Handle all returned errors as flagged by golangci-lint
- Propagate errors instead of calling Fatalf
- Refactored runCharon to propagate the error if cmd.Start() fails.
Note that prior, cmd.Wait() would've returned an error if cmd.Start()
failed and and thus immediately exited via Fatalf but I think it's cleaner
to propagate the error via StartEngine.
> Cleanup error handling in ipsec

- main.go
- pkg/controllers/tunnel/tunnel.go
* Id → ID (e.g. ClusterId → ClusterID)
* Api → API (e.g. ApiKey → APIKey)
* Drop unused import and unnecessary type specification in main.go
* tunnel.TunnelController → tunner.Controller to avoid stuttering
> golint clean-ups

- .gitignore
- Dockerfile.dapper
- main.go
- pkg/util/util.go
- pkg/util/util_suite_test.go
- pkg/util/util_test.go
- scripts/test
Coverage is about 83% - most uncovered lines are on hard-to-hit error paths.
The ParseSecure function was refactored a bit to return errors, as is
declared in the signature, instead of calling Fatalf to exit - it should let
the caller handle the returned error and decide if it's fatal (which the lone
caller does). This also made it easier to write tests for the error conditions.
FlattenColors was modified to handle a null or empty input array so the test
case passes.
The second commit is a follow-up to address a comment wrt GetClusterCRDName.
> Added unit tests for util.go using ginkgo

- Dockerfile.dapper
Executing make validate will fail because we're not installing
goimports inside the dapper container.
This commit installs goimports inside dapper.
> Fix scripts/validate in dapper

- test/e2e/framework/network_pods.go
This allows the formatting part of scripts/validate script to pass
again.
> Format network_pods.go

- pkg/client/clientset/versioned/clientset.go
- pkg/client/clientset/versioned/fake/clientset_generated.go
Ran the submariner v1 types with the newer 1.14.1 version of the
k8s code generator. The only changes are removal of deprecated
functions.
> Update k8s generated code

- pkg/controllers/datastoresyncer/datastoresyncer.go
- pkg/datastore/datastore.go
- pkg/datastore/kubernetes/kubernetes.go
- pkg/datastore/phpapi/phpapi.go
- pkg/util/util.go
- pkg/util/util_test.go
Several Datastore methods pass or return by value rather than pointers.
Change to pointers for efficiency. This also cascaded to a couple util
methods.
> Change Datastore methods to use pointers

- pkg/util/util_test.go
- scripts/lib/find_functions
- scripts/test
- scripts/validate
Skip one test that calls an unsuported netlink function in OSX,
the test will be skipped when the error is "not implemented".
Modify the scripts/test to make the find call compatible with OSX
and linux, also speeding up execution by avoiding "vendor" and
other unnecessary directories being explored by find.
Remove clutter from ginkgo output making it much cleaner.
> OSX unit test running compatibility and speedups

- main.go
- pkg/datastore/phpapi/phpapi.go
- Handle all returned errors as flagged by golangci-lint
- Propagate or log errors instead of calling Fatalf
- Improved logging messages where appropriate
- Return error for unimplemented method
> Cleanup error handling in phpapi

- pkg/cableengine/cableengine.go
- pkg/cableengine/ipsec/ipsec.go
- pkg/controllers/tunnel/tunnel.go
The Engine and Specification structs do not need to be
exported and NewEngine can return the implemented interface
type.
Also renamed the CableEngine interface to Engine to reduce stutter -
so now it reads cableengine.Engine.
> Refactor ipsec to hide implementation

- scripts/lib/find_functions
This reduces the number of processes and filters involved in building
the list of packages, significantly reducing the execution time.  We’d
removed the dynamic construction of the directory list in
scripts/validate, this restores it.
> Simplify find, restore it in scripts/validate

- scripts/test
- scripts/validate
The dirname $0 output is relative, so if we cd first,
and then try to source the lib/find_utils script, it won't
work.
This patch fixes the issue.
> Fix validate and test scripts

- Dockerfile.dapper
gcc, ca-certificates, vim, less, and file are all unused.
> Remove unused packages from the Dapper container

- scripts/kind-e2e/README.md
Fix various minor typos in the Kind-based end-to-end testing docs.
Remove docs about requirement for SELinux to be set to permissive, as
that is no longer a requirement.
> Fix typos in e2e test README, rm selinux=off docs

- Dockerfile.dapper
Because gcc is not present in the build container, the E2E ginkgo tests are failing with error:
exec: "gcc": executable file not found in $PATH
Steps to reproduce:
1. make e2e status=clean
2. docker system prune --all
3. make e2e
> GCC fix for E2E ginkgo tests

- pkg/util/util.go
https://github.com/submariner-io/submariner/pull/95 modified the
imports so they're no longer sorted which fails goimports.
> Fix goimports error in util.go

- pkg/controllers/datastoresyncer/datastoresyncer.go
- scripts/validate
The script was running:
`golangci-lint run -D megacheck -E unused,gosimple,staticcheck`
With these flags, the `unused` linter does not actually run (I assume `gosimple` and `staticcheck` don't run either) as there is unused code submariner (`datastoresyncer`). Running just `golangci-lint run` yields errors emitted by `unused`.
I'm not clear as to the purpose of these flags. It isn't necessary to explicitly enable `unused`, `gosimple` and `staticcheck` as they are enabled by default. FWICT, `megacheck` runs `staticcheck`, `gosimple` and `unused` at once for efficiency - I don't know the reason for disabling it but doing so seems to also disable the other 3 even though they are explicitly enabled.
> Remove golangci-lint command flags in validate script

- scripts/ci
Now that validation works reliably, let's ensure it's enabled in CI
builds. Run validation first, then tests, before the builds
themselves.
> Enable validation in CI, test before build

- package/Dockerfile.routeagent
This switches to the publicly-available RHEL8-based UBI image. The
resulting image is 134 MiB in size.
> Switch to UBI8 for the route agent image

- pkg/cableengine/ipsec/driver.go
- pkg/cableengine/ipsec/ipsec.go
- pkg/cableengine/ipsec/strongswan.go
In order to support other IPsec drivers, the Driver interface has been
introduced to encapsulate the requirements from the IPsec engine.
The IPsec engine has some business logic and iptables related code which
isn't related to the way it actually connects the tunnels, so that code
remains in the engine, while the tunnel specific things have been
extracted.
The implementation has been extracted as-is, with as little changes as
possible (other than the obligatory ones to actually allow the new
interface) so that the refactor is easy to understand.
Currently the StrongSwan implementation is created hard coded, but the
aim is to add a LibreSwan driver type in the next patches.
> Extract strongswan to a Driver in ipsec

- pkg/cableengine/cableengine.go
- pkg/cableengine/ipsec/driver.go
- pkg/cableengine/ipsec/ipsec.go
- pkg/cableengine/ipsec/strongswan.go
- pkg/controllers/tunnel/tunnel.go
This is based on a request from PR #99 to make the remove side use endpoint instead of the cable name, and let the engine/driver use whatever it desires from the endpoint to remove the connection.
It should be rebased once #99 is merged.
> Remove cable endpoint

- README.md
If you don't cd into the directory, all the ginkgo output is hidden at commandline:
[ajo@rhvirt-casa submariner]$ go test ./test/e2e/ -args -ginkgo.v -ginkgo.randomizeAllSpecs -dp-context cluster2 -dp-context cluster3 -report-dir output/junit/
ok  	github.com/submariner-io/submariner/test/e2e	32.277s
Reverts submariner-io/submariner#105
> Revert "Update Readme (running e2e tests without changing directory)"

- scripts/codegen
The switch to using go mod broke the codegen script as 'go get' now
places the downloaded k8s.io/code-generator repo in the go mod cache which
is not intended to be accessed directly. So I changed it to use git
clone.
> Fix codegen script

- scripts/kind-e2e/e2e.sh
The issue is that the removed line overrides the main KUBECONFIG exported after the initial run and recurring runs with status=keep fail.
> Fix e2e recurring runs

- scripts/kind-e2e/cluster2-config.yaml
- scripts/kind-e2e/cluster3-config.yaml
- scripts/kind-e2e/e2e.sh
This PR uses [Cluster.networking.disableDefaultCNI](https://github.com/kubernetes-sigs/kind/issues/278) option for clusters 2 and 3. After the container nodes are up we are installing weave manually. In previous setup with k8s version 1.14.1, weave was ignoring podCidr provided in kind config file and used its default 10.32.0.0/12 cidr as podCidr. This PR fixes this issue.The result is a cluster with weave and podCidr that is taken from kind config file. This removes the need to be constrained to specific k8s version or kind version. After this is merged kind can be safely upgraded. Other types of cni plugins can be tested more easily.
> [E2E] Use weave as default cni for all k8s and kind versions. 

- scripts/kind-e2e/e2e.sh
Currently the clusterCidr information used to configure
Submariner has wrong values. This patch fixes it.
> Fix clusterCidr used in configuring Submariner

- scripts/build
- scripts/build-routeagent
- scripts/ci
- scripts/codegen
- scripts/download
- scripts/e2e
- scripts/entry
- scripts/lib/version
- scripts/package
- scripts/release
- scripts/test
- scripts/validate
- scripts/vendor
Using "git rev-parse" to find debug_functions means that our build only works in _our_ git repository. This makes a number of scenarios difficult: building from a release archive, building within another git repository, etc. The result is that Submariner becomes harder to package...
The version script only makes sense when sourced; enforce that and move the script to lib.
> Reduce git rev parse

- scripts/kind-e2e/e2e.sh
submariner-io/submariner-charts helm repository is hosting the latest charts from gh-pages branch.
The charts info is available at https://submariner-io.github.io/submariner-charts/charts/index.yaml.
> Point the helm chart configuration to submariner-io/submariner-charts

- scripts/kind-e2e/e2e.sh
- scripts/lib/debug_functions
This avoids having to call trap_commands at the start of every
function.
> Enable extdebug to propagate trap_commands

- package/Dockerfile.routeagent
- package/iptables
- package/iptables-save
Depends-On: https://github.com/submariner-io/submariner-charts/pull/3
Both iptables and nftables use netfilter framework in the kernel for
packet filtering. Many distributions are moving in the direction of
using nftables over iptables. Although, nftables uses a new command
line utility (named nft), starting from iptables >=1.8, it uses
nftables under the hood while continuing to support the same iptables
syntax from the user.
Quoting from Dan's comment [#]
"In iptables 1.8, the maintainers have "deprecated" the classic ip_tables:
the iptables tool now does userspace translation from the legacy UI/UX,
and uses nf_tables under the hood. So, the commands look and feel the
same, but they're now programming a different kernel subsystem.
The problem arises when you mix and match invocations of …
> Exec iptables from the host filesystem

- go.mod
- go.sum
Go 1.13 requires longer git SHA-1 prefixes, and checks the timestamp
exactly. This patch fixes the strongSwanVICI fork prefix and
timestamp, and updates the 1.13 dependencies in go.sum.
> Update checksums for Go 1.13

- pkg/routeagent/controllers/route/route.go
When deploying a K8s/OpenShift Cluster on AWS, multiple Availability Zones (AZs) are
used for maximized service availability. Each AZ uses a CIDR (f.e., 10.165.32.0/20)
thats pulled out of the VPC Global CIDR (f.e., 10.165.0.0/16).
Currently in Submariner, we are deriving the VxLAN VTEP IP address from the host-ip as
shown below.
For example: Say, the host ipaddress is "192.168.1.100/16", we were prepending 240 to
the host-ip address and configuring the vxlan vtepIP as "240.168.1.100/16"
This works fine when all the nodes are on the same Subnet CIDR, but will have issues
when programming inter-cluster routing rules on the host via the vx-submariner interface.
Error message:
route.go:719] Error adding route {Ifindex: 58 Dst: 10.252.0.0/14 Src: <nil>
Gw: 240.165.41.54 Flags: [] Table: 0}: …
> Fix network unreachable issue on AWS with multiple AZs

- test/e2e/dataplane/tcp_pod_to_service.go
- test/e2e/framework/framework.go
- test/e2e/framework/network_pods.go
- test/e2e/framework/pods.go
- test/e2e/framework/services.go
Before this patch, E2E didn't have any control of where pods
landed, this made the testing of different scenarios random.
With this patch we ensure the testing of the datapath when
traffic needs to transit from a worker node to a gateway node.
Cluster type has been converted to an enumeration as part of this
commit.
> E2E scheduling of pods to GW/NonGW nodes

- go.mod
- go.sum
- package/Dockerfile
- package/charon.conf
- pkg/cableengine/ipsec/strongswan.go
- pkg/cableengine/ipsec/strongswan_test.go
Some corporate networks block outgoing IPSEC traffic ports,
in such cases the option to specify no standard IPSEC ports
becomes necessary.
This patch allows control over the IPSEC UDP ports. All clusters
must use the same ports. In the future we should implement
the ability to declare which ports a cluster uses, and announce
those through the exchanged endpoint information.
The environment variables are:
- CE_IPSEC_IKEPORT   defaults to 500
- CE_IPSEC_NATTPORT  defaults to 4500
> Allow IPSec on non-standard ports via environment variables

- scripts/lib/debug_functions
This avoids issues caused by the extdebug bug in Bash < 4.4.
Closes: https://jira.coreos.com/browse/HYCLD-263
> Use set -T instead of shopt -s extdebug

- package/submariner-route-agent.sh
- package/submariner.sh
The current entrypoints were using a flag `--debug` that is not
processed by the executables they run. Therefore, when setting
`SUBMARINER_DEBUG` environmental variable the container crashed
and entered a crash loop. Moreover, the debug env var was not taking
care of putting `charon` in debug mode.
This patch fixes this issues by removing the flag `--debug`.
> Fix entrypoints to support debug correctly

- operators/go/submariner-operator/pkg/controller/submariner/submariner_controller.go
- operators/go/submariner_controller.go.nolint
- scripts/kind-e2e/lib_operator_verify_subm.sh
The helm charts and the operator differ on the DaemonSet name,
this patch makes that uniform so the verification logic works for
both equally.
This also fix deploying with helm.
> Fix operator deployment to use submariner-routeagent DaemonSet

- operators/go/submariner-operator/pkg/controller/submariner/submariner_controller.go
By the default the operator will use version 0.0.2 of the submariner
components from quay.io/submariner.
> Make operator use released version 0.0.2 of submariner

- scripts/kind-e2e/e2e.sh
- scripts/kind-e2e/lib_operator_verify_subm.sh
-it is only useful for interactive use, and makes it difficult to run
the tests non-interactively (e.g. piped to less).
> Drop -it from exec

- operators/go/gen_subm_operator.sh
- operators/go/submariner-operator/deploy/operator.yaml
- operators/go/submariner-operator/version/version.go
After initial SubM Operator merge, bump version to "release" 0.0.1 and
make 0.0.2 the under-dev version.
> Bump Operator version 0.0.1->0.0.2

- scripts/release
This follows the model used for engine and routeagent images: CI tags
successful builds with :latest and the git SHA, and pushes them to
Quay.
> Tag the operator images

- README.md
- scripts/build
- scripts/build-engine
- scripts/ci
- scripts/e2e
- scripts/kind-e2e/README.md
This will avoid the double-build of engine, routeagent and operator,
because they are built once for ci, and once again for e2e which
was not expected.
We start doing what documentation says, make compiles/builds, and e2e
just runs e2e with an existing build, README.md says:
```
To build `submariner-engine` and `submariner-route-agent` you can
trigger `make`, which will perform a Dapperized build of the components.
To run basic e2e tests you can trigger `make e2e` command.
```
> Uncouple ci building from e2e

- Dockerfile.dapper
This gives us more up-to-date software and allows us to use packaged
versions of Go and kubectl.
> Switch to Fedora for the Dapper image

- package/Dockerfile.dapper-base
- scripts/package
- scripts/release
This will allow us to publish an image upon which we can build our
Dapper images, which avoids a lot of downloading and rebuilding all
the time. For now the image is amd64-only.
> Add base Dapper image

- go.mod
- scripts/kind-e2e/e2e.sh
- scripts/test
- Adding the usage of Ginkgo PR onsi#601: `-ginkgo.reportFile <file path>`
- Fix (remove) ansi colors around test steps in E2E Junit report
> Generate Junit reports for all Packages and E2E tests

- package/Dockerfile.routeagent
The routeagent build is based on registry.access.redhat.com/ubi8/ubi-minimal:latest/8.1 image that has an issue with microdnf. 
process:6): libdnf-WARNING **: 06:10:10.893: Loading "/etc/dnf/dnf.conf": IniParser: Can't open file
The command '/bin/sh -c microdnf -y install --nodocs iproute iptables && microdnf clean all' returned a non-zero code: 141
This issue also affects fedora:30 container images when microdnf is used instead of dnf.
https://github.com/rpm-software-management/microdnf/issues/50
The issue is not present in the registry.access.redhat.com/ubi8/ubi-minimal:8.0.
> [Urgent] Fix for microdnf issue with the latest ubi image

- test/e2e/framework/api_errors.go
- test/e2e/framework/framework.go
- test/e2e/framework/network_pods.go
- test/e2e/framework/nodes.go
- test/e2e/framework/pods.go
- test/e2e/framework/test_context.go
Added some helper functions for upcoming e2e enhancements.
> Add helper functions for e2e tests

- scripts/kind-e2e/cluster1-config.yaml
- scripts/kind-e2e/e2e.sh
One of the test scenarios requires dynamically
adding/removing third cluster to the setup.
The idea is to use broker cluster as the third
cluster.
This patch just installs SubM on broker cluster
but does not tag any gateway nodes. Node is tagged
later in the test case to mimic adding third cluster.
Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>
> Install SubM on broker cluster

- scripts/kind-e2e/e2e.sh
Recent changes to install subm on the brooker cluster caused a
failure when waiting for the subm pods to be ready b/c no
gateway node is configured so the engine isn't deployed. Removed
the code to wait for the pods.
> Fix E2E setup script failure

- test/e2e/framework/network_pods.go
addNodeSelectorRequirement hard-codes the Operator and Values fields
and thus a non-gateway node is always selected for the connectivity check
pods. Use the parameters.
> Fix pod scheduling in E2E

- README.md
- pkg/routeagent/controllers/route/driver.go
- pkg/routeagent/controllers/route/route.go
Reverse path filtering is a mechanism used by networking devices to check whether a receiving packet
source address is routable. When reverse path filtering is enabled, the host will first check whether
the source of the received packet is reachable through the interface it came in. If it is routable
through the interface in which it came, then the packet is accepted otherwise its dropped.
When using flannel CNI, we have to configure loose mode for reverse path filtering and this patch
automates this change.
rp_filter - INTEGER
0 - No source validation.
1 - Strict mode as defined in RFC3704 Strict Reverse Path
Each incoming packet is tested against the FIB and if the interface
is not the best reverse path the packet check will fail.
By default failed packets are discarded.
2 - Loose mode …
> Fix for Flannel CNI

- package/iptables-save.sbin.wrapper
- package/iptables.sbin.wrapper
- package/submariner-route-agent.sh
On some platforms, iptables binary is installed on /sbin instead of /usr/sbin.
In the current code, we were only checking /usr/sbin folder. This patch includes
even /sbin in the list of folders that are evaluated for the presence of iptables
utility on the host.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner/223)
> Use hosts /sbin/iptables when available

- package/Dockerfile.routeagent
The previously merged PR #223 did not include the sbin wrapper
scripts in the docker image, and when iptables is detected under
the /sbin directory on the host it will fail with the following error:
cp /usr/sbin/iptables-save.sbin.wrapper /usr/sbin/iptables-save
cp: cannot stat '/usr/sbin/iptables-save.sbin.wrapper': No such file or directory
This commit fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner/224)
> Include the sbin iptables wrappers

- scripts/kind-e2e/e2e.sh
Issue:
Running make ci e2e status=keep multiple times locally.
Currently after the first initial run, the broker cluster has submariner engine installed with helm. The pods are not healthy as we don't tag gateway nodes for broker cluster and not loading the images to cluster1. This results in a check for submariner pods always to be false and forces a recurring installation of the engine with helm. The engine on the broker cluster is needed only for testing purposes so this PR makes the installation occur only once during the broker installation phase on cluster1. 
Error:
Error: a release named submariner already exists.
Run: helm ls --all submariner; to check the status of the release
Or run: helm del --purge submariner; to delete it
---
This change is [<img …
> Fix for make ci e2e recurring runs with helm

- go.mod
When running:
```
make ci e2e status=keep
```
I got: 
```
[submariner]$ go test -v -race -cover . ./pkg/... -ginkgo.reportPassed -ginkgo.reportFile junit.xml
?       github.com/submariner-io/submariner     [no test files]
?       github.com/submariner-io/submariner/pkg/apis/submariner.io/v1   [no test files]
?       github.com/submariner-io/submariner/pkg/cableengine     [no test files]
flag provided but not defined: -ginkgo.reportFile
Usage of /tmp/go-build675420303/b402/ipsec.test:
-ginkgo.debug
If set, ginkgo will emit node output to files when running in parallel.
-ginkgo.dryRun
If set, ginkgo will walk the test hierarchy without actually running any
```
Investigating showed that reportFile 
- absent from v1.10.2: https://github.com/onsi/ginkgo/blob/v1.10.2/config/config.go#L104
- …
> go.mod: upgrade to ginko v1.10.3

- go.mod
- scripts/kind-e2e/README.md
- scripts/kind-e2e/e2e.sh
Execution of the e2e tests takes around 2 minutes, if only the local
testing environment is required, the tests can be skipped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner/228)
> Allow to create a test env. without running e2e test

- package/submariner-route-agent.sh
On some platforms, its seen that iptables on the host is a symlink to a file
(f.e, /etc/alternatives/iptables) which again is a symlink to another file
(f.e., /usr/sbin/iptables-legacy). On such platforms, with the current code,
when we validate the presence of iptables using "[[ -x /host/usr/sbin/iptables ]]",
it fails since "-x" dereferences the symbolic links and the symlink would point to
a file on the container file system (instead of checking the host filesystem).
This patch uses chroot with the host-filesystem for validating the presence of iptables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner/227)
> Use chroot to verify iptables on the host

- package/Dockerfile.routeagent
This applies the published workaround for
https://github.com/rpm-software-management/microdnf/issues/50 allowing
us to track :latest again.
> Work around the UBI8 microdnf bug

- scripts/kind-e2e/e2e.sh
In an existing Submariner (with globalnet) deployment, when we re-run
the command "make build package e2e status=keep", the following error
is seen and this patch fixes it.
kubectl --context=cluster2 -n submariner create serviceaccount submariner-globalnet
Error from server (AlreadyExists): serviceaccounts "submariner-globalnet" already exists
[submariner]$ ./scripts/e2e keep 1.14.2 false false helm false
FATA[0224] exit status 1
make: *** [Makefile:18: e2e] Error 1
> Fix build issue when re-running the build in an existing setup

- package/Dockerfile.routeagent
- package/iptables-save.sbin.wrapper
- package/iptables-save.wrapper
- package/iptables-wrapper.in
- package/iptables.sbin.wrapper
- package/iptables.wrapper
- package/submariner-route-agent.sh
This avoids having path-specific wrappers. The patch also documents
why we can’t use the Kubernetes approach.
> Use a common iptables wrapper

- package/Dockerfile.globalnet
- package/submariner-globalnet.sh
- pkg/globalnet/controllers/ipam/constants.go
- pkg/globalnet/controllers/ipam/globalnet.go
- pkg/globalnet/controllers/ipam/globalnet_egress.go
- pkg/globalnet/controllers/ipam/globalnet_ingress.go
- pkg/globalnet/controllers/ipam/ipam.go
- pkg/globalnet/controllers/ipam/types.go
- pkg/routeagent/controllers/route/iptables.go
- pkg/util/util.go
- scripts/kind-e2e/globalnet/deploy-globalnet-2.yaml
- scripts/kind-e2e/globalnet/deploy-globalnet-3.yaml
This patch implements the following
1. Spawns Globalnet Controller on the GatewayNode
2. Initializes Globalnet Controller only when the Cluster uses kubeproxy
3. Programs necessary egress rules for PODs
4. Programs necessary ingress rules for ClusterIPServices
> Implement globalnet ingress and egress features

- scripts/kind-e2e/e2e.sh
PR https://github.com/submariner-io/submariner/pull/228/ modified e2e.sh so
it only runs the E2E tests if 'status=keep' and thus the tests no longer run
with 'status=onetime', which is the default via 'make ci e2e' as documented.
Therefore modified e2e.sh to also check for 'status=onetime'.
> E2E tests not running by default

- pkg/globalnet/controllers/ipam/ippool.go
`available` shouldn't be accessed unprotected.
> IpPool.IsAvailable should lock

- README.md
This lists the steps involved to download and install subctl somewhere
on the PATH.
> Add more details for subctl installation

- .travis.yml
With local branches, and automatically created ones travis is doing extra unnecessary work duplication. This fixes it. 
Pull requests will be tested regardless of this, but changes to specific branches  (not through PRs) will be ignored.
> Only build master branch, ignoring local branches

- test/e2e/cluster/add_remove_cluster.go
It's failing frequently on travis, it seems due to some random initial delay
when settng up vxlan tunnels. See https://github.com/submariner-io/submariner/issues/257.
> Disable add cluster E2E test for now

- pkg/globalnet/controllers/ipam/ippool.go
This function is coded to return the existing allocated IP, if any, however the
IsFull check elides that if there's no available IPs. I assume this isn't
the intent so remove the up-front check as this case is handled anyway by the
subsequent code.
> Remove IsFull check in IpPool.Allocate

- test/e2e/dataplane/tcp_pod_connectivity.go
- test/e2e/framework/framework.go
- test/e2e/framework/network_pods.go
- test/e2e/framework/test_context.go
Added 'connection-timeout' and `connection-attempts' test params.
Defaults are 6 and 10 for total timeout of 60 s.
> E2E: make connection timeout configurable

- pkg/apis/submariner.io/v1/types.go
- pkg/apis/submariner.io/v1/zz_generated.deepcopy.go
There is a growing need to be able to support multi cluster networking
across brownfield deployments that have limited abilities to create non
overlapping CIDRs for their Pod(s) and Service(s) networks. As discussed
during some meetings this can be addressed by having a Global multi
cluster network that is non-overlapping and can do NATting while still
be able to leverage the advantages that Submariner brings.
This patch adds the ability to define a Global CIDR segment associated
with a specific cluster and store the information as part of the
cluster's Cluster CRD. The autogenerated part was added by executing
`./scripts/codegen`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Add Global CIDR to Cluster CRD

- main.go
- pkg/types/types.go
- pkg/util/util.go
The Cluster CRD has now support for a Global CIDR segment. However,
`submariner-engine` is not aware of it and thus it cannot properly
react to it. The `submariner-routeagent` uses the information stored on
each Endpoint CRDs to set routes based on the Subnets each Endpoint acts
as a gateway for. Therefore, `submariner-agent` needs to populate that
information with the correct Subnets. That means current behavior if
the Global CIDR is not present or the Global CIDR otherwise.
This patch allows `submariner-agent` to properly handle this case. For
this it introduces a new environmental variable `SUBMARINER_GLOBALCIDR`
which when present tells `submariner-agent` that the Global CIDR is to
be preferred over the Service and Pod CIDRs.
> Support Global CIDR in submariner-engine

- pkg/apis/submariner.io/v1/types.go
- pkg/apis/submariner.io/v1/zz_generated.deepcopy.go
- pkg/routeagent/controllers/route/route.go
- pkg/routeagent/main.go
Currently the `submariner-agent` makes use of `Cluster` CRDs to set
up the routes. This, however, is information that is more natural to
the `Endpoint` CRD as it describes the subnets that are to be found
when connecting that endpoint. Moreover, having a single source of
truth instead of two simplifies the code and allows for easier
integration with `submariner-globalnet`.
This patch makes the `Endpoint` be the source of truth for setting up
routes. By doing so, there is no need for the `submariner-routeagent` to
monitor `Cluster`s anymore and therefore the code that is related has
been removed, simplifying the codebase in consequence.
> Use Endpoint CRD to configure routes

- package/Dockerfile.globalnet
- package/submariner-globalnet.sh
- pkg/globalnet/controllers/ipam/ippool_test.go
This PR fixes two issues.
1. Patch [https://github.com/submariner-io/submariner/pull/251] removed an
API from ippool, but the associated unit tests were not updated. This
patch fixes those issues.
2. PR [https://github.com/submariner-io/submariner/pull/232] modified the
iptable wrappers. Similar changes are required in the globalnet controller.
> Fix build issues on the overlapping-cidrs branch

- .travis.yml
- scripts/kind-e2e/e2e.sh
The following change [https://github.com/submariner-io/submariner/pull/254]
modifies travis configuration to validate only master branch ignorning local
branches. Since we are interested in validating overlapping-cidrs branch,
this PR enables overlapping-cidrs as part of travis configuration.
Along with this, it also fixes a build issue with submariner-operator.
> Enable CI on overlapping-cidrs branch

- pkg/globalnet/controllers/ipam/constants.go
- pkg/globalnet/controllers/ipam/gatewaymonitor.go
- pkg/globalnet/controllers/ipam/globalnet.go
- pkg/globalnet/controllers/ipam/globalnet_egress.go
- pkg/globalnet/controllers/ipam/globalnet_ingress.go
- pkg/globalnet/controllers/ipam/ipam.go
- pkg/globalnet/controllers/ipam/types.go
- pkg/globalnet/main.go
- scripts/kind-e2e/globalnet/deploy-globalnet-2.yaml
- scripts/kind-e2e/globalnet/deploy-globalnet-3.yaml
- scripts/kind-e2e/globalnet/role-globalnet.yaml
This patch implements the following features
1. Modifies the Globalnet controller to a DaemonSet with
nodeSelector so that it gets scheduled on all the nodes
labelled with submariner.io/gateway: "true"
2. Initializes ipamController only on the active GatewayNode
of the Cluster. On all the other nodes, we just keep
monitoring for any leader changes and react accordingly.
3. When a clusterLeader (aka GatewayNode) migrates to a new
node, ipamController running on that node will be stopped
and all the existing globalnet ingress/egress rules are
deleted. On the new clusterLeader, ipamController will
be initialized and it reprograms the necessary ingress,
egress rules.
4. Inorder to support the above use-cases and to optimize
the flow, globalnet ingress and egress rules are now
programmed in …
> Enhancements to Submariner Globalnet Controller

- test/e2e/framework/deployments.go
- test/e2e/framework/framework.go
- test/e2e/framework/nodes.go
- test/e2e/framework/submariner_resources.go
- test/e2e/redundancy/gateway_failover.go
Two gateway nodes configured with 2 submariner engine replicas. This tests
the leader election fail-over.
> Add third gateway fail-over E2E scenario test

- test/e2e/redundancy/gateway_failover.go
While we're transitioning the subm engine from Deployment to
DaemonSet in the helm chart and operator...
> Temporarily disable gateway E2E

- pkg/globalnet/controllers/ipam/gatewaymonitor.go
Currently, when the gateway node transitions to a new node in a cluster,
the code tries to delete the globalnet-marking rule for the current cluster
on the non-gw node. This results in a (non-fatal) error message as part of
logs. This patch fixes it.
Signed-off-by: Sridhar Gaddam sgaddam@redhat.com
> Avoid deleting the globalnet-marking rule on non-gw node

- pkg/globalnet/controllers/ipam/gatewaymonitor.go
- pkg/globalnet/controllers/ipam/ipam.go
- pkg/globalnet/controllers/ipam/types.go
- scripts/kind-e2e/globalnet/deploy-globalnet-2.yaml
- scripts/kind-e2e/globalnet/deploy-globalnet-3.yaml
- scripts/kind-e2e/globalnet/role-globalnet.yaml
Currently, globalCIDR is configured/stored as part of clusterCRD and
Submariner uses this value to populate the endpoint subnets. At the
same time, globalnet controller is reading this value as an environment
parameter in the globalnet POD. Storing/reading globalCIDR from two
different places could be error prone if not configured/deployed properly.
This patch modifies globalnet controller to read the globalCIDR from the
clusterCRD which is the source of truth for a cluster.
> Use globalCIDR from ClusterCRD

- scripts/kind-e2e/e2e.sh
In long-past debugging/fixing activities, our CI folks thought this
timeout needed to be longer for some deployments. In recent discussions,
I've confirmed that it no longer needs to be so long. Set it to the same
300s used elsewhere in similar timeouts.
See comments here:
github.com/submariner-io/submariner/pull/273#discussion_r367435417
> Decrease weave-net pod deployment timeout

- Makefile
- scripts/dapper-image
- scripts/package
When packages/Dockerfile.dapper-base is modified it will be detected
and the image will be regenerated locally.
The base dapper image is built and published from the master branch
so if any change has happened between the upstream master branch
and the local files, the local dapper image will be rebuilt
before any other build procedure is handled.
> Handle local dapper-base changes when necessary

- pkg/routeagent/controllers/route/driver.go
- pkg/routeagent/controllers/route/iptables.go
- pkg/routeagent/controllers/route/route.go
- pkg/util/util.go
Currently, Submariner configures necessary tunnels and routing rules to
support connectivity between the PODs in different Clusters. However, if
we try to connect from the underlying host to a remotePOD/Service it does
not work. While working on some of the Storage use-cases in K8s, we realized
that connectivity from underlying Host to remoteCluster is required. This
patch addresses this use-case.
Fixes Issue: https://github.com/submariner-io/submariner/issues/298
> Support Connectivity from HostNetwork to RemoteCluster

- .travis.yml
Fixes: https://travis-ci.com/submariner-io/submariner/builds/146943642#L168
See: https://stackoverflow.com/questions/31278233/disadvantages-of-shallow-cloning-on-travis-and-other-ci-services
> Fix branch merge issues where travis CI is unable to checkout the branch sha

- .travis.yml
This would help tracing how long the e2e scripts take on each step.
> Add timestamps on make runs

- pkg/routeagent/controllers/route/route.go
- pkg/routeagent/controllers/route/vxlan.go
During gateway node migration, on some occasions, it was observed
that there was an error while adding an FDB entry which results
in PANIC and route-agent pod gets restarted. The reason why FDB
entry failed is because of trying to configure an FDB entry with
empty ipAddress. This patch fixes this issue by ensuring that we
wait until a POD gets an IPAddress and process it only after one
is assigned to it.
Fixes issue: https://github.com/submariner-io/submariner/issues/331
> Fix PANIC in route-agent pod during gw migration

- test/e2e/cluster/add_remove_cluster.go
- test/e2e/dataplane/tcp_pod_connectivity.go
- test/e2e/redundancy/gateway_failover.go
- test/e2e/tcp/connectivity.go
Moved RunConnectivityTest, RunNoConnectivityTest, et al from dataplane
to a new "tcp" module/package. This separates the actual connectivity code
from the dataplane Ginko specs so one can use the connectivity test code
from other specs w/o also causing the dataplane specs to run.
> Move TCP connectivity test functions to new module

- scripts/kind-e2e/lib_operator_deploy_subm.sh
When installing KIND based K8s clusters using the operator as
shown below[#], the initial deployment goes fine. However, when
we try to redeploy (i.e, re-run the same command), it's failing.
[#] make ci e2e status=keep deploytool=operator
Fixes issue: https://github.com/submariner-io/submariner/issues/337
> Fix KIND redeployment error when using operator

- test/e2e/framework/deployments.go
- test/e2e/redundancy/gateway_failover.go
This PR updates the e2e tests to validate fail-over use-cases when
Submariner engine is deployed as a DaemonSet.
> Update e2e redundancy tests for SM engine deployed as DaemonSet

- scripts/kind-e2e/e2e.sh
- scripts/kind-e2e/lib_helm_deploy_subm.sh
When installing KIND based K8s clusters using helm[#], the initial
deployment goes fine. However, when we try to redeploy (i.e, re-run
the same command), it's failing and this PR fixes it.
[#] make ci e2e status=keep deploytool=helm
Fixes issue: https://github.com/submariner-io/submariner/issues/339
> Fix KIND redeploy issue when using helm

- main.go
In an HA setup where multiple nodes are labelled as Gateway
nodes, when the active SubmarinerEngine/Node goes down, it takes
about 15+ seconds for one of the backup Submariner Gateway PODs
to become active. This patch makes the leader election values
configurable along with some defaults that reduce this interval.
> Reduce gateway failover detection interval

- README.md
As part of the overall 0.1.0 release, we should tell users to download
subctl v0.1.0.
> Use v0.1.0 in the download instructions

- scripts/kind-e2e/lib_operator_deploy_subm.sh
If we can’t determine the latest version of subctl using the GH API,
default to v0.1.0.
> Default to subctl v0.1.0

- Makefile
vendor/modules.txt is updated whenever "go mod vendor" is run, so we
can use that to track vendor freshness compared to go.mod. This avoids
problems with an already-present but out-dated vendor directory when
we add or update dependencies.
> Vendor as needed

- pkg/workqueue/queue.go
Wraps a rate-limiting workqueue and the boilerplate to reduce
code duplication in users.
> Add workqueue wrapper

- .travis.yml
Split Travis CI configuration into three jobs to reduce execution time
through parallelism and achieve better test coverage of both
Operator-based and Helm-based deployments.
Instead of using the meta "ci" make target in both Operator/Helm jobs,
use the more narrow build/package targets and extract the common
test/validate to a third job. This reduces duplication and total can
shorten time-till-results.
Closes: #283
> Split CI into jobs for more concurrency, coverage

- pkg/routeagent/controllers/route/route.go
- pkg/util/stringset.go
- pkg/util/stringset_test.go
StringSet exposed the Set field publicly which is unsafe.
The Set was accessed and iterated unprotected by code in route.go.
Made the field package-scoped and added an Elements method to return
a new []string. Also updated the unit tests.
> Hide the Set field and add Elements method to StringSet

- pkg/client/clientset/versioned/typed/submariner.io/v1/fake/failing_cluster.go
- pkg/client/clientset/versioned/typed/submariner.io/v1/fake/failing_endpoint.go
...that provide mocking failures with return errors as the generated fake impls don't provide this.
> Add fake SubmarinerEndpoint and SubmarinerCluster implementations

- .gitignore
Ignore:
* Various junit test results files throughout the repo.
* Encoded datafiles for specific local cluster configs, perhaps many
from previous runs.
* Old/crashed/running local dapper config files.
> Add dynamic/ephemeral files to gitignore

- pkg/routeagent/controllers/route/route.go
- pkg/workqueue/queue.go
The default exponential rate limiter uses a maxDelay of 1000 sec or ~16 min
which is reached on the 19 retry:
1: 5ms
2: 10ms
3: 20ms
4: 40ms
5: 80ms
6: 160ms
7: 320ms
8: 640ms
9: 1.28s
10: 2.56s
11: 5.12s
12: 10.24s
13: 20.48s
14: 40.96s
15: 1m21.92s
16: 2m43.84s
17: 5m27.68s
18: 10m55.36s
19: 16m40s
Even the 15th retry is over a minute. This is too long - we should cap it lower.
I picked 30 sec - same as the resync period.
Also changed the new submariner workqueue for when the route agent is migrated to use it.
> Use lower maxDelay for route agent rate limiter

- .travis.yml
The previous syntax resulted in only the second environment variable
being set. Put all env vars for each job on a single line.
Relates to: #396
> Fix Travis env var syntax

- go.mod
- pkg/datastore/kubernetes/kubernetes.go
In the current implementation, when the ClusterCRD is updated, its seen
that there is a race loop between the old and the new CRD on the Broker
cluster as well as local cluster. Basically, datastore syncer that watches
the cluster and endpoint CRDs on the broker cluster was notifying the
change even when the CRDInfo belongs to the localCluster.
The source of truth for the clusterCRD and endpointCRD would be the local
cluster and not the information on the Broker Cluster. This patch includes
appropriate checks in the datastoresyncer to notify only changes associated
to remote clusters.
Fixes issue: https://github.com/submariner-io/submariner/issues/366
> Fix race loop when ClusterCRD is updated with globalCIDR

- .travis.yml
- scripts/release
* Deployment should only happen from one of the branches
* When built on a tag, images will not be :dev , but :v0.x.x ($VERSION)
> Fix CI deploy

- pkg/datastore/datastore.go
- pkg/datastore/kubernetes/kubernetes.go
- pkg/datastore/phpapi/phpapi.go
Simplifies implementations and unit tests. We can add functions
back if ever needed.
> Remove unused functions in Datastore interface

- Makefile
- go.mod
- scripts/kind-e2e/e2e.sh
- scripts/kind-e2e/lib_helm_deploy_subm.sh
- test/e2e/dataplane/tcp_pod_connectivity.go
- test/e2e/e2e.go
- test/e2e/framework/test_context.go
This patch includes support in KIND (deploytool=helm) for deploying
Globalnet controller.
Usage:
make ci e2e status=keep deploytool=helm globalnet=true
Fixes issue: https://github.com/submariner-io/submariner/issues/381
> Support for deploying Globalnet Controller with KIND/Helm

- go.mod
- scripts/kind-e2e/e2e.sh
Currently, KIND clusters are deployed with non-overlapping CIDRs (pod and svc).
Inorder to validate Globanetnet Controller, we require clusters with overlapping
CIDRs and this PR addresses it.
> Deploy Clusters with Overlapping CIDRs when globalnet is true

- .travis.yml
Currently, we have two jobs which validate Submariner deployments
using Helm and Operator. Since we have limited resources on CI,
instead of creating new jobs for globalnet, this PR modifies the Helm
job to validate globalnet Controller.
> Validate Globalnet Controller (deploytool=helm) in CI

- go.mod
- test/e2e/e2e.go
- test/e2e/framework/framework.go
- test/e2e/framework/logging.go
- test/e2e/framework/submariner_resources.go
- test/e2e/framework/test_context.go
This is a follow-up to https://github.com/submariner-io/submariner/pull/363
to co-locate the globalnet check with clientset creation to avoid code
duplication and to have it in a normal Gingko test code path. To avoid re-creating the clientsets and performing the check for every test via `BeforeEach`, these were moved to a `BeforeSuite` function which is invoked from the top-level `SynchronizedBeforeSuite` in **e2e.go**. Since `Framework` instances are created locally per set of tests and there can only be one `BeforeSuite` defined and should be at the top-level, the clientsets are now defined and set in the global `TestContext`. The equivalent fields in `Framework` remain for now - their access sites can be migrated in another PR.
> E2E: move clientset creation et al to BeforeSuite

- scripts/kind-e2e/e2e.sh
When deploying a KIND cluster with globalnet=true, and for some
reason if the globalnet controller fails to annotate the nginx-demo
service with a globalIp, KIND should fail with an appropriate error
message.
Fixes Issue: https://github.com/submariner-io/submariner/issues/440
> Fix error message when globalnet fails to annotate a service

- pkg/util/util.go
- pkg/util/util_test.go
Original EndpointSpec comparisons were limited to `ClusterID`, `CableName` and the `Hostname`. 
In the case of wireguard it is not enough. 
This PR adds to comparison `Backend` and `BackendConfig`.
> Extend EndpointSpec comparisons

- Makefile
- scripts/build
- scripts/build-engine
- scripts/build-globalnet
- scripts/build-routeagent
- scripts/ci
- scripts/kind-e2e/e2e.sh
Convert e2e.sh to use getopt to accept parameters, vs positional
agreements. This makes calls more robust against breakages from changes
and doesn't require callers to be aware of all params.
Supports reusing e2e.sh and related scripts in other submariner-io/*
project CI systems.
Closes: #420
> Use getopt for robust params in e2e.sh

- .travis.yml
- Makefile
Default to using submariner-operator to deploy SubM vs Helm. The
Operator is already the deploy method used for the job that publishes
built images, and seems to be generally considered the more important
of the two deploy methods. It will likely get the most attention going
forward.
> Default to Operator-based SubM deploys, vs Helm

- package/Dockerfile.dapper-base
This makes the following changes:
* avoid pulling in weak dependencies on distrosync
* clean out a number of unnecessary packages
* compress the large Go binaries we end up installing
removing 400 MiB from the image (1.83 GiB down to 1.43 GiB).
> Shrink the dapper-base image

- Makefile
In order to reduce the churn of unnecessary tasks, only perform these
make targets when we're not trying to clean the e2e tests.
> Skip dapper targets if status is clean

- scripts/kind-e2e/README.md
- scripts/kind-e2e/e2e.sh
Allows for more robust use across submariner-io/* CIs, where the scripts
will be live in and be addressed from different locations.
Relates to: #369
> Use portable paths for kind-e2e files

- go.mod
- scripts/kind-e2e/lib_operator_deploy_subm.sh
Now that we modified Submariner Engine as a DaemonSet, as-soon-as
the label is removed from the node, SM engine pod will be terminated.
> Cleanup deploytool_postreqs in operator deployment

- .travis.yml
e2e submariner WireGuard cable tests require WireGuard modules on the testing host. 
This PR installs WireGuard.
> install WireGuard

- pkg/globalnet/controllers/ipam/ipam.go
This PR temporarily removes the check for Kubeproxy validation.
Proper handling will be done in subsequent PR.
Workarounds-Issue: #458
> Validate the presence of kubeproxy

- pkg/globalnet/controllers/ipam/globalnet.go
- pkg/globalnet/controllers/ipam/globalnet_ingress.go
Services without selectors i.e no backend pod, are not accessible across clusters if globalnet is enabled. It works when clusters don't have overlapping CIDRs and globalnet is not used.
This PR addresses this issue by supporting services without selectors along with fixing an issue in the iptables chain name used by kube-proxy.
Fixes issue: https://github.com/submariner-io/submariner/issues/460
> Globalnet: Annotate services without selectors

- pkg/globalnet/controllers/ipam/constants.go
- pkg/globalnet/controllers/ipam/ipam.go
Current implementation of Globalnet Controller works only with
iptables based kube-proxy. This PR includes necessary validation
as part of initialization and returns appropriate error message
when cluster does not use kube-proxy.
Fixes issue: https://github.com/submariner-io/submariner/issues/458
> Return error when kubeproxy is missing in the cluster

- Dockerfile.dapper
Cleaned up environment var which aren't necessary and weren't working
properly anyhow as they relied on DAPPER_SOURCE which is defined in the
same line.
Resolves: #477
> Clean up dapper dockerfile

- Makefile
- go.sum
- scripts/kind-e2e/cluster_settings
Due to https://github.com/submariner-io/shipyard/pull/70 the created
"clusters" are too small for the E2E tests. Hence, changing back to the
previous setting in SubM E2E until we find a better way to address this.
> Unbreak SubM CI

- Makefile.dapper
Because we’re invoking Make through Dapper, the usual
environment-based flag handling doesn’t work.
> Make sure the child Make gets the parent flags

- package/Dockerfile
This removes a number of unused packages, without breaking any
dependencies (it should also be possible to remove systemd...). This
reduces the image size by 50MiB.
> Shrink the Submariner container image

- Makefile
- scripts/reload-images
This target will push the images to the localhost registry on the clusters
so the developer can subsequently set imagePullPolicy to always on the desired
resource and force it to reload. Alowing a very quick developer cycle.
> Add reload-images makefile target

- .travis.yml
- scripts/codegen
The API codegen script had stopped running because we don't run it often,
this fixes the script and runs it as part of the unitest/validation job
in travis.
> Fix codegen script and run in travis

- Dockerfile.dapper
We're using the release procedure from shipyard, which needs these env
variables available inside the dapper.
> Pass release env variables to dapper

- go.mod
- go.sum
- pkg/globalnet/controllers/ipam/gatewaymonitor.go
- pkg/globalnet/controllers/ipam/globalnet.go
- pkg/globalnet/controllers/ipam/globalnet_egress.go
- pkg/globalnet/controllers/ipam/ipam.go
- pkg/globalnet/controllers/ipam/types.go
- pkg/routeagent/controllers/route/driver.go
- pkg/routeagent/controllers/route/route.go
- test/e2e/dataplane/tcp_gn_pod_connectivity.go
This PR includes a set of commits that support the use-case of connecting from HostNetwork to remoteService globalIP when using Globalnet.
Fixes Issue: https://github.com/submariner-io/submariner/issues/464
Depends-Onː https://github.com/submariner-io/submariner-charts/pull/20
Depends-Onː https://github.com/submariner-io/submariner-charts/pull/21
Depends-Onː https://github.com/submariner-io/submariner-operator/pull/304
Depends-Onː https://github.com/submariner-io/shipyard/pull/94/
> Globalnet: Host Network to remoteService globalIP connectivity

- test/e2e/redundancy/gateway_failover.go
This increases the timeouts for tests, which are not enough sometimes and
generate random failures, and also fixes the gateway failover tests which
could detect a pod in the wrong host just by the fact that the new label
did't have time to trigger / complete the transition.
Fixes: #304
> Re-enable and fix Gateway failover tests

- package/Dockerfile
The build of the submariner Dockerfile started failing locally
probably due to changes in fedora, and another rpm package
needs to be removed.
> Fix rpm -e failure due to unmet dependencies.

- Makefile
- scripts/kind-e2e/e2e.sh
This allows consecutively re running the e2e tests without going through
the (reenrant, yet still time consuming) deploy process.
> Deploy "lazily" so that e2e can be re run

- .github/ISSUE_TEMPLATE/committership.md
- .github/ISSUE_TEMPLATE/membership.md
Add GitHub Issue templates to help aid the Submariner community
membership process, in particular Committer and Member requests.
Relates-to: #499
> Add Committer/Member request templates

- Makefile
- scripts/kind-e2e/README.md
- scripts/kind-e2e/e2e.sh
This PR addes the new e2e-tests target, as well as a focus env var which allows filtering e2e tests to be ran.
```
make e2e-tests focus=gateway
```
Will run only the e2e tests tagged as [gateway]
> Allow running only the e2e part, and focusing on specific tests

- main.go
- pkg/cableengine/syncer/syncer.go
- test/e2e/framework/framework.go
- test/e2e/redundancy/gateway_failover.go
Without this patch an active gateway pod could die and not
be respawn (no available passive node...) and in the meanwhile
nobody would remove the Gateway entry, appearing still reported
as active, connected etc...
> Remove gateway entry when gateway pod exits

- pkg/routeagent/controllers/route/driver.go
- pkg/routeagent/controllers/route/route.go
This PR returns an appropriate error message if we are unable to determine
the CNI Interface on the host at an early stage. Otherwise, the errors could
manifest at later stage making it difficult to understand what is going wrong.
Related to# https://github.com/submariner-io/submariner/issues/529
> Return error if CNIIface is not discovered

- main.go
On some platforms, it was seen that the active leader node sometimes (not
frequent though) is unable to renew the lease for leaderLock and because
of this Gateway POD is getting restarted. In one of the earlier PRs, we
reduced these intervals to improve the failover detection. In this PR we
are increasing the interval slightly until we find a proper solution to
handle HA.
Related to# https://github.com/submariner-io/submariner/issues/540
> Tweak leader election timings

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/failing-test.md
- .github/ISSUE_TEMPLATE/flaking-test.md
- .github/ISSUE_TEMPLATE/support.md
Add GitHub Issue templates for reporting bugs, requesting enhancements,
reporting test failures, or reporting flaky tests.
The templates are based on the kubernetes/kubernetes repository examples.
> Add templates for bugs/features/failing/flaking

- pkg/globalnet/controllers/ipam/ipam.go
- scripts/validate
The new version of golangci-lint points out a type-casting issue in
ipam, which can be fixed by instantiating a new variable of the
appropriate type in a generic manner.
Running the updated linter also requires a new timeout, and excluding
the clientset (which is generated code and therefore not useful to
lint).
> Fix type handling for linting

- Dockerfile.dapper
- scripts/kind-e2e/e2e.sh
- scripts/validate
Seems it was pinned down by mistake, unpin it
Also fixed a bug on the lazy deployment, due to recent Shipyard changes
> Unpin shipyard image

- Makefile.dapper
The host could be different from linux or have a weird path for make.
Fixes: #555
> Don't pass the make binary path down to dapper

- test/e2e/framework/framework.go
Otherwise when used from verify-connectivity it will fail, because we don't pass contexts
and also, the context could be different from the cluster name.
Related-Issue: https://github.com/submariner-io/submariner-operator/issues/381
Related-PR: https://github.com/submariner-io/submariner-operator/pull/382
> Framework E2E detection should be independent of cluster IDs

- package/Dockerfile.globalnet
- package/Dockerfile.routeagent
https://github.com/rpm-software-management/microdnf/issues/50 was
fixed in UBI 8.2 (see https://access.redhat.com/errata/RHEA-2020:1855
for details), so we no longer need the workaround.
(If this fails to build locally, make sure to refresh your UBI 8
image.)
> Remove UBI 8 microdnf --nodocs workaround

- pkg/globalnet/controllers/ipam/gatewaymonitor.go
- pkg/globalnet/controllers/ipam/types.go
- pkg/globalnet/main.go
- pkg/routeagent/controllers/route/route.go
- pkg/util/util.go
Submariner supports clusters with Overlapping CIDRs (via Globalnet) as well as
clusters with non-overlapping CIDRs. However, if administrator accidentally tries
deploying submariner with wrong configuration, Submariner should log a warning
message and avoid making changes in the local cluster which otherwise can disrupt
the functionality of the local cluster.
This PR specifically validates the following and logs an appropriate warning.
1. In a Vanilla Submariner deployment, if administrator is trying to join clusters
with Overlapping Pod/Service CIDRs.
Note: For such clusters, Submariner Globalnet should be used.
2. In a Globalnet deployment, if GlobalCIDRs are overlapping across the clusters.
3. In a Globalnet deployment, if localCluster Pod/Service CIDRs overlap with globalCIDR
of other …
> Validate CIDRs before making changes to the Cluster

- .github/workflows/e2e.yaml
- pkg/cable/driver.go
- pkg/cable/libreswan/libreswan.go
- pkg/cable/strongswan/strongswan.go
- pkg/cable/strongswan/strongswan_test.go
- pkg/cable/wireguard/driver.go
- pkg/cable/wireguard/getconnections.go
- pkg/cableengine/cableengine.go
**Add the Cluster Spec as input during driver creation:**
- Cross-cluster traffic from pods on host network are assigned the source address of the WG interface, according to the routing rules; therefore, this should be an allowed IP
- The driver looks for a valid address within the local node interfaces; however, with GN, the allowed IPs (`localSubnets`) passed to driver are GN CIDRs and do not match any local interface IP
- Cluster CIDR is now used to look for a valid IP if not found in `localSubnets`
- GN will SNAT this address to a the GN CIDR, which is an allowed IP for the WG tunnel
**Misc**
- For better robustness, a FW mark was added to WG interface to block any circular routing, in case there is a routing rule back to WG device 
- More debug logging.
> Wireguard: better localIP discovery search

- main.go
- pkg/cable/driver.go
- pkg/cable/libreswan/libreswan.go
- pkg/cable/strongswan/strongswan.go
- pkg/cable/strongswan/strongswan_test.go
- pkg/cable/wireguard/driver.go
- pkg/cableengine/cableengine.go
The cable driver currently takes separate arguments for subnets and
endpoint, but the endpoint includes the subnet information. This patch
removes the separate subnets argument.
> Remove separate subnet arguments

- .github/workflows/e2e.yaml
- package/Dockerfile
- package/pluto
- pkg/cable/libreswan/libreswan.go
- pkg/cable/libreswan/libreswan_suite_test.go
- pkg/cable/libreswan/libreswan_test.go
This relies on the whack command-line tool for now. Because the
full-blown status is very hard to parse, the connection-tracking code
uses the simpler trafficstatus output, which doesn’t give all the
information we’d really need but is sufficient to determine whether a
connection is active or not.
We set up one tunnel per subnet pair, one tunnel between the hosts,
and one tunnel between each host and each opposing subnet.
Fixes: #592
Fixes: #385
Fixes: #564
>  Support Libreswan "cable" creation

- .github/workflows/e2e.yaml
Wireguard now fails to build because a recent commit in the kernel
(https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2c64605b590edad)
moved various skb helpers to skbuff.h, and changed Wireguard’s
queueing.h to use them. The kernel we get in the test setup doesn’t
have this change, so the current Wireguard module package no longer
builds.
This patch changes the Wireguard setup to check for the change in
skbuff.h, and apply a revert patch to queueing.h if it isn’t present.
> Fix the Wireguard workaround

- pkg/globalnet/controllers/ipam/gatewaymonitor.go
- pkg/globalnet/controllers/ipam/globalnet.go
When the submariner.io/gateway label is deleted from the node, k8s deletes
the submariner engine and also the submariner globalnet pod from that node.
It was seen that when the globalnet pod is terminated, it was only deleting
SUBMARINER-GN-MARK chain and not the other chains like SUBMARINER-GN-INGRESS
and SUBMARINER-GN-EGRESS. This is causing random failures in CI for the
globalnet jobs.
In this PR we handle this by ensuring that when globalnet pod is terminated,
it will cleanup the associated iptable rules that were programmed on that node.
Fixes Issue: https://github.com/submariner-io/submariner/issues/596
> Cleanup globalnet rules when globalnet pod is migrated

- pkg/globalnet/controllers/ipam/globalnet.go
- pkg/globalnet/controllers/ipam/ipam.go
Currently, Globanet annotates the Pod/Service/Nodes with globalIP and programs
necessary ingress/egress rules on the node. However, if there is an issue while
programming the iptable rules, its not handled.
This PR fixes it and also annotates the Pod/Service/Nodes only after it successfully
programs the necessary ingress/egress rules on the Gateway node.
Fixes Issue: https://github.com/submariner-io/submariner/issues/595
> Annotate globalIp only after programming ingress/egress rules

- pkg/globalnet/controllers/ipam/constants.go
- pkg/globalnet/controllers/ipam/globalnet.go
- pkg/globalnet/controllers/ipam/ipam.go
In order to support hostNetwork to remoteCluster connectivity, globalnet needs
the CNIInterfaceIP of all the worker nodes. The CNIInterfaceIP for the nodes is
annotated by submariner-route-agent. However, submariner-route-agent runs ONLY
on the worker nodes and not on the master nodes. Globalnet controller has a
listener for nodes and will wait for this annotation before it can program rules
for HostNetwork to remoteCluster support. In the current code, the master nodes
are constantly getting re-queued as the annotation will never be added on such
nodes.
In this PR we check if the node is capable of scheduling pods (aka worker node)
and only process (or re-queue) such nodes.
Fixes Issue: https://github.com/submariner-io/submariner/issues/553
Signed-off-by: Sridhar Gaddam …
> Globalnet Controller to skip annotating master nodes with globalIp

- .github/workflows/e2e.yaml
The Azure kernel headers apparently don't have skbuff.h in the
expected place, so instead of checking that, look explicitly for
version -1020- of the kernel. This avoids failing the builds on kernel
1022 which includes an updated skbuff.h and doesn't need the Wireguard
patch.
> Avoid relying on skbuff.h

- package/Dockerfile
The DNF layer adds about 50MB (out of which several are due to
distrosync).
Removing stuff actually doesn't clean much since most of these packages
were already there in the base image, so it saves around 7MB but makes
the whole thing needlessly complicated.
We can live with a few extra MB but a much simpler Dockerfile
> Don't try to shrink submariner image

- pkg/cable/libreswan/libreswan.go
For NAT connections, the local side always uses the private IP
address, not the public IP address, and the routed subnets always use
the private IP addresses. The public IP address is only used for the
remote end of the connection.
> Fix NAT on Libreswan

- package/Dockerfile
- package/submariner.sh
Like the route agent and globalnet containers, the engine container
needs to use the host iptables.
This requires a corresponding change in the deployment settings (in
the operator and Helm charts).
> Use the host iptables in the engine

- .travis.yml
The job is broken, and replaced by GitHub Actions anyway.
> Stop testing the Helm deployment in Travis

- pkg/cable/wireguard/README.md
- pkg/cable/wireguard/driver.go
@mangelajo 
- Add PSK support (environment variable: `CE_IPSEC_PSK`)
- Allow changing WG port (environment variable: `CE_IPSEC_NATTPORT`, default 5871)
- updated README
**Limitations / TODO**
- Using the ipsec env prefix and env variable names
common options should probably use a common submariner env prefix
- Should probably move the env parsing out of driver and use common code for all cables
- UDP listen port should be part of the endpoint configuration -- allow endpoints to use different ports
> support pre-shared key in wireguard

- pkg/cable/libreswan/libreswan.go
In the function which starts the IKE daemon, wait for it to start (up
to 5s) before returning. This helps avoid races when starting the
gateway; if we don't wait, the daemon starts alongside the gateway,
and in some cases we end up trying to set tunnels up before the daemon
is ready, resulting in delays (the tunnels aren't set up until the
next resync round).
> Wait for Pluto to start

- .github/workflows/e2e.yaml
The DKMS package is no longer installed by default, but we still need
it.
> Install wireguard-dkms

- Makefile
Since we dont need them to just create the kind clusters, they should be
built only if we plan to deploy.
Also deploy should depend on images, which would make sure the images
are up to date. No need for deploy target to depend explicitly on build.
> Only build images for `deploy`

- pkg/cable/libreswan/libreswan.go
GetActiveConnections from cable drivers is supposed to return the
list of created cables instead of the connected cables.
If we only return connected ones connections will eventually get
replicated.
Related-Issue: #642
> libreswan: do not replicate connections in list

- pkg/cable/libreswan/libreswan.go
Connection initiation is now done asynchronously, so whack --initiate
won't keep waiting if the other side isn't ready (eliminating potential
timing issues).
If whack fails we retry at least 3 times (as we did for strongswan vici
connections).
Fail hard on any whack exit error, which will result on a later retry
because the endpoint is enqueued for retry by the cable engine.
Closes-Issue: #642
> libreswan: initiate connections asynchronously and retry whacks (stricter err checking)

- pkg/routeagent/controllers/route/route.go
- pkg/util/stringset.go
This PR implements the necessary support in route-agent code to enable
remote cluster connectivity from a Pod on GatewayNode with HostNetworking
for libreswan cable driver.
Along with this, it also fixes an issue with Strongswan (inc' globalnet)
where the sourceIP of such traffic was not properly configured to the
CNIInterfaceIP of the GatewayNode.
Fixes issue: https://github.com/submariner-io/submariner/issues/635
> libreswan: HostNetworking on GW to remote cluster support

- pkg/cableengine/fake/cableengine.go
- pkg/cableengine/syncer/syncer.go
- pkg/cableengine/syncer/syncer_test.go
- pkg/client/clientset/versioned/typed/submariner.io/v1/fake/failing_gateways.go
The code intended to update `StatusFailure` but instead returned the error thus eliding the update.
Also handle nil from `ListConnections` to be safe.
This PR also adds unit tests for the cable engine `Syncer` and corresponding changes in a series of small commits.
> Update Gateway StatusFailure when ListConnections fails

- pkg/cableengine/syncer/syncer.go
- pkg/cableengine/syncer/syncer_test.go
As per comment in https://github.com/submariner-io/submariner/pull/687.
I also had to push https://github.com/submariner-io/submariner/pull/690/commits/4eb60092feb0e38ab027084a59535e07a808d95a to fix a race failure during the validation check.
> Simplify GatewayStaleTimeout calculation

- test/e2e/cluster/add_remove_cluster.go
The latest release of golangci-lint (1.28.0) now flags this as an error
via the newer version of the gosimple linter. Fix before upgrading the
version in Shipyard to keep the verify job here passing.
> Remove unnecessary use of Sprintf

- pkg/cable/wireguard/getconnections.go
- pkg/controllers/datastoresyncer/datastoresyncer.go
- pkg/routeagent/controllers/route/route.go
When looping over a range, if a value variable is declared, the range
can be copied before processing; this means that passing a pointer to
a range value can cause issues. Using the index to address slice items
avoids a copy and means that pointers to slice items are canonical.
> Avoid exposing range pointers

- .golangci.yml
- pkg/types/types.go
Saves a few bytes of memory by aligning structures with themselves
better, without requiring padding.
> Enable maligned memory linting, fix issue

- pkg/cable/libreswan/libreswan.go
Comparing the index and the length isn't particularly useful, and
confuses linters (and reviewers).
> Libreswan: simplify connection removal

- .golangci.yml
- main.go
- pkg/controllers/datastoresyncer/datastoresyncer.go
- pkg/controllers/datastoresyncer/datastoresyncer_suite_test.go
- pkg/datastore/fake/datastore.go
- pkg/datastore/kubernetes/kubernetes.go
- pkg/globalnet/controllers/ipam/ipam.go
- pkg/globalnet/main.go
- pkg/routeagent/controllers/route/route.go
- pkg/routeagent/main.go
Enable golangci-lint lll line length linting, set max length at 140 chars.
> Enable lll line length linting, fix errors

- .golangci.yml
With golangci-lint 1.28.0, scopelint is now obsoleted and the
recommendation is to use exportloopref. Remove (commented, suggestion)
config for scopelint and enable exportloopref.
> Enable exportloopref linter

- .golangci.yml
- main.go
- pkg/cable/libreswan/libreswan_test.go
- pkg/cable/strongswan/strongswan.go
- pkg/cable/strongswan/strongswan_test.go
- pkg/cable/wireguard/driver.go
- pkg/cable/wireguard/getconnections.go
- pkg/cableengine/cableengine.go
- pkg/cableengine/fake/cableengine.go
- pkg/controllers/datastoresyncer/datastoresyncer.go
- pkg/controllers/datastoresyncer/datastoresyncer_suite_test.go
- pkg/datastore/fake/datastore.go
- pkg/globalnet/controllers/ipam/globalnet.go
- pkg/globalnet/controllers/ipam/ipam.go
- pkg/globalnet/controllers/ipam/ippool.go
- pkg/routeagent/controllers/route/route.go
- pkg/routeagent/controllers/route/vxlan.go
- pkg/util/util.go
Disable if-else chain linting as it seems to only flag false positives
in our code base. Our two violations don't switch on a single condition,
so while one of them can be written as a switch, it's less clear.
> Enable gocritic linting, fix errors

- pkg/routeagent/controllers/route/route.go
Route-agent pod was unnecessarily waiting on a waitGroup which was
leading to issues during pod termination. This PR fixes it.
Partially fixes: https://github.com/submariner-io/submariner/issues/694
> Fix shutdown path in Submariner Route-agent Pod

- main.go
In the current code, it was seen that GatewayPod was not handling the
shutdown signal properly and was finally getting terminated by K8s
after the terminationGracePeriod interval is exhaused. This is because
leaderelection.RunOrDie does not return. This PR fixes it by running
the leaderelection in a Goroutine and using stopCh to wait for shutdown
signal.
Partially fixes: https://github.com/submariner-io/submariner/issues/694
> Fix shutdown path in Submariner Gateway Pod

- pkg/routeagent/controllers/route/route.go
Normally, most of the platforms are configured with hostname without the domainname.
However, on AWS, for one of the nodes, it was seen that hostname was configured as
FQDN (i.e., hostname.domainname) while all the remaining nodes were configured with
just the hostname alone. Because of this, route-agent was failing to start on that
node. This PR fixes it.
Fixes issue: https://github.com/submariner-io/submariner/issues/736
> AWS: Fix missing cniIfaceIP annotation for Node (pr2)

- package/Dockerfile.submariner
... to avoid issues with the Fedora registry. Given that the libreswan
package pulls in Python, the practical differences between the minimal
and main images aren’t significant for us anyway.
> Use the main Fedora image

- package/pluto
The pluto launcher should exec pluto to avoid leaving a shell process.
> Exec pluto

- main.go
The gateway synchronizer will handle the removal when the stopCh is closed.
The synchronizer removal happens here: https://github.com/submariner-io/submariner/blob/38ff81bf48a8d1709b60c2b3793646528585de31/pkg/cableengine/syncer/syncer.go#L45
Fixes-Issue: #765
> Fixes double gateway entry removal

- .gitlint
Allow short body lines, for example GH's "Relates-to"/"Closes".
Ignore commits from Dependabot, as it doesn't follow our conventions.
> Tweak gitlint rules

- README.md
The Helm repository specified in the README was incorrect and would cause deployments to fail. This MR tells users of the Helm chart to use the `submariner` GitHub repository directly.
Fixes #743.
> Fix Helm repo in README.md

- main.go
check https://github.com/submariner-io/submariner-operator/issues/461#issuecomment-680021600
> Remove a possible race condition during  WireGuard driver initialization 

- pkg/routeagent/controllers/route/route.go
On Rancher cluster, it was observed that OS.Hostname was configured
as "node-01.example.com" whereas the corresponding nodeName was "node-01".
This was not handled in the code and was causing RouteAgent to fail.
This PR fixes it.
Fixes Issue: https://github.com/submariner-io/submariner/issues/736
> Fix route-agent error on Rancher cluster

- CODEOWNERS
As discussed during the Submariner community meeting [1], we will
be enabling "enforcement on admin of CI and votes", but with CODEOWNERS
as they work on github (they are not additive, and every time you add a new line
the previous "codeowners" aren't anymore) will make some files depending
on a single person precluding others core contributors from merging patches
when necessary.
This was proposed as a solution during the meeting.
[1] https://docs.google.com/document/d/1qnZ2LpF_rXGfnYYPNTldQ4WbeEUxwnuQD-xTC6GbZdg/edit#heading=h.ek692hgyg1a4
> Make CODEOWNERS additive before enabling admin enforcement

- pkg/apis/submariner.io/v1/types.go
So that we can generate the Gateway CRD automatically, annotate the
Gateway type with the appropriate directive to generate the additional
printer column.
> Annotate to declare the Gateway print column

- pkg/cable/cleanup/default_cleanup.go
- pkg/cable/cleanup/route_cleanup_handler.go
- pkg/cable/cleanup/xfrm_cleanup_handler.go
- pkg/cable/strongswan/strongswan.go
- pkg/routeagent/cleanup/cleanup.go
- pkg/routeagent/controllers/route/cleanup_handling.go
- pkg/routeagent/controllers/route/route.go
This removes technical debt where specific knowledge
related to cable drivers was implemented in the route-agent.
Introduces an interface which can be exposed from multiple
places, for example can be used by [1] to improve the
separation of concerns in the code.
[1] https://github.com/submariner-io/submariner/pull/762
Co-authored-by: Sridhar Gaddam <sgaddam@redhat.com>
> Add a cleanup handling interface to route agent

- tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/ec2-resources.tf
We should not set the submariner security group as cluster-owned,
otherwise the LoadBalancer controller stops working, because that's
not supported.
```text
Warning  SyncLoadBalancerFailed  16s (x4 over 53s)  service-controller
Error syncing load balancer: failed to ensure load balancer:
Multiple tagged security groups found for instance i-03fcabdc39f37f25c;
ensure only the k8s security group is tagged; the tagged groups were
sg-06cf365995bf20f3f(majopela-cluster-a-09-b7ch5-submariner-gw-sg)
sg-0c4abc1fcf12d5c3b(terraform-20200922090409222000000002)
```
> Remove the cluster owned tag from submariner sg

- tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/machine-set-resources.tf
- tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/templates/machine-set.yaml
This commit makes use of our new support for taints making
the submariner gateway node dedicated to submariner, selecting
a network specific instance type which supports higher bandwidth
in Amazon EC2. We also remove an attached volume that it's not
necessary.
> AWS Terraform scripts: m5n.large and dedicated instance

- .github/workflows/unit.yml
- Makefile
Use the new "unit" target provided by Shipyard for running unit tests,
instead of remapping Shipyard's "unit-test" to "test" and using that.
> Replace "test"/"unit-test" make targets with "unit"

- .github/workflows/linting.yml
The current validate job arbitrarily groups MD and Go linting. Split
them into two different jobs for clarity.
> Split validate job into Go and MD jobs

- test/e2e/framework/framework.go
Needed to enable latency and throughput intra-cluster tests
https://github.com/submariner-io/submariner-operator/issues/706
> Change framework e2e test to allow testing with only 1 cluster

- .github/workflows/e2e.yml
- .github/workflows/linting.yml
- .github/workflows/periodic.yml
- .github/workflows/release.yml
- .github/workflows/unit.yml
Currently using a mix of v1 and master. Instead, use the latest
everywhere.
> Use v2 of GHA checkout action everywhere

- .github/workflows/linting.yml
- .golangci.yml
We now ship yamllint with Shipyard, so use that instead of a third-party
GitHub Action.
Also fix a YAML warning flagged by `make yamllint`.
> Use Shipyard-provided yamllint, not GHA

- pkg/cableengine/cableengine.go
When Submariner is deployed in a Cluster with NAT disabled, the local endpoint
of the cluster includes the external-ip (aka public-ip) of the active gateway
node. The active gateway node of the cluster updates the endpoint info on the
Broker which is subsequently sync'ed by all the member clusters. The member
clusters then try to connect to the public-ip configured in the endpoint CRD
to setup IPsec tunnels. When the external-ip (or public-ip) of an endpoint
changes, tunnels should be reconfigured successfully with the new public-ip.
This is not happening in the current code and this PR fixes it.
Fixes Issue: https://github.com/submariner-io/submariner/issues/826
Co-authored-by: Aswin Surayanarayanan <asuryana@redhat.com>
> Handle external-ip changes on Gateway node

- pkg/cable/cleanup/route_cleanup_handler.go
- pkg/cable/cleanup/xfrm_cleanup_handler.go
- pkg/globalnet/cleanup/gn_cleanup.go
- pkg/globalnet/controllers/ipam/constants.go
- pkg/globalnet/controllers/ipam/gatewaymonitor.go
- pkg/globalnet/controllers/ipam/globalnet.go
- pkg/globalnet/controllers/ipam/globalnet_egress.go
- pkg/globalnet/controllers/ipam/globalnet_ingress.go
- pkg/globalnet/controllers/ipam/ipam.go
- pkg/routeagent/cleanup/cleanup.go
- pkg/routeagent/constants/constants.go
- pkg/routeagent/controllers/route/cleanup_handling.go
- pkg/routeagent/controllers/route/constants.go
- pkg/routeagent/controllers/route/iptables.go
- pkg/routeagent/controllers/route/route.go
In the current implementation of Globalnet, when the Globalnet Pod
is restarted, the datapath goes down as Globalnet controller flushes
the IPTable chains that support inter-cluster connectivity.
In this PR we move the cleanup to RouteAgent Pod which does the cleanup
(aka flushing of iptable chains) when there is a Gateway migration.
This PR also moves the IPTable Chain names to routeAgent code to avoid
cyclic dependency and to have all the chain names at a single place.
Fixes Issue: https://github.com/submariner-io/submariner/issues/721
> Preserve datapath when GlobalnetPod is restarted

- .github/workflows/linting.yml
DCO checks fail on jobs triggered by tags.
It shouldn't be necessary to run linting on tags, as the code was
already gated by PR-triggered jobs.
> Don't run linting on tags

- .github/workflows/e2e.yml
- .github/workflows/unit.yml
Following up on the change to not run linting on tags, it doesn't seem
to make sense to run anything other than the release workflow on tags.
The assumption was these jobs would be clearly shown by the tags,
documenting for users which checks were successfully run against that
tag at the time. Looking at our tags and releases in more detail, that
doesn't seem to be the case. Each commit in the repo history shows the
job results, but that's it.
> Don't run unit or E2E tests on tags

- tools/openshift/ocp-ipi-aws/prep_for_subm.sh
Otherwise configuring multiple clusters with prep_for_subm.sh as we explain
on the quickstarts [1] does not work, and the machineset yaml files
are overwritten.
[1] https://submariner.io/quickstart/openshift/service_discovery/
Fixes-Issue: #876
> Download and keep the Terraform state inside the cluster directory

- test/e2e/framework/framework.go
Related to: submariner-io/submariner-operator#748
This will enable using any By() method set in the framework
Usefull when running tests with verbose=false
> Call framework.By instead of ginkgo in e2e framework beforeSuite

- main.go
- pkg/controllers/tunnel/tunnel.go
- pkg/controllers/tunnel/tunnel_test.go
- test/e2e/framework/framework.go
- test/e2e/redundancy/gateway_failover.go
The tunnel controller doesn't actually sync a k8s resource but it does transform an Endpoint to a tunnel connection and thus can use the `ResourceSyncer` infrastructure to eliminate a lot of informer/event handler boilerplate.
Relatee to #375
> Simplify/Refactor tunnel controller to use ResourceSyncer

- tools/openshift/ocp-ipi-aws/versions.tf
Currently, while preparing the AWS cluster for Submariner as
part of prep_for_subm.sh script, we only support terraform
version 12.x
In this PR, we display an appropriate error message if users
are trying to run the script with a different version of terraform.
> Alert user the supported terraform version in prep_for_subm.sh

- pkg/event/event_suite_test.go
- pkg/event/handler.go
- pkg/event/logger/handler.go
- pkg/event/registry.go
- pkg/event/registry_test.go
This registry will be used later by the networkplugin-syncer or the route-agent.
> Eventhandler registry

- CODE-OF-CONDUCT.md
It seems most CNCF projects provide a CODE-OF-CONDUCT.md file at the
root of their repositories, even if they have their Code of Conduct on
their website. To better fit into the CNCF ecosystem and be a more
welcoming project, follow that pattern.
Relates-to: #804
> Add CODE-OF-CONDUCT.md, point to website

- .github/workflows/codeowners.yml
Validate that changes to CODEOWNERS/CODEOWNERS.in are the same generated
by the gen-codeowners script.
> Add CI for CODEOWNERS generation

- CODEOWNERS.in
Trying to line up rows of files with a number of tabs varying by the
length of the code owner's GitHub username is difficult to maintain and
consistently achieve readable rendering.
Instead, use a single space after each code owner handle.
> Use single space vs tab alignment in CODEOWNERS.in

- pkg/globalnet/main.go
When Submariner is installed in a Cluster, the local ClusterCRD is
created by the submariner-gateway pod. While the submariner-gateway
pod is in the process of initializing itself if Globalnet pod tries
to read the ClusterCRD it will be missing. In this PR, we modify
Globalnet code to retry for 5 mins before giving up.
Fixes issue: https://github.com/submariner-io/submariner/issues/903
> Wait for ClusterCRD in Globalnet during initialization

- README.md
Some README badges link to workflows on the master branch, others just
to the workflow generally. Remove the master filter, as it doesn't show
any jobs for some workflows and few jobs for others.
> Remove master branch filter from badge links

- pkg/event/controller/controller.go
- pkg/event/controller/controller_test.go
- pkg/networkplugin-syncer/main.go
A race condition with the `registry` field:
```
Write at 0x00c0003a3fa0 by goroutine 9:
github.com/submariner-io/submariner/pkg/event/controller_test...
/go/src/github.com/submariner-io/submariner/pkg/event/
controller/controller_test.go:43
Previous read at 0x00c0003a3fa0 by goroutine 21:
github.com/submariner-io/submariner/pkg/event.(*Registry).invokeHandlers()
/go/src/github.com/submariner-io/submariner/pkg/event/registry.go:141
github.com/submariner-io/submariner/pkg/event.(*Registry).StopHandlers()
/go/src/github.com/submariner-io/submariner/pkg/event/registry.go:67
```
This is due to the test starting the controller in a Go routine but not waiting for it to complete. There's another intermittent failure related to fake client sets/informers that is also due to the async Start.
To fix …
> Fix intermittent event controller test failures

- go.mod
- go.sum
- pkg/event/logger/handler.go
This becomes more useful by not printing the whole object blobs, we
just need small informative lines to understand that the events
are happening and when.
> Reduce the logger event handler log footprint

- pkg/apis/submariner.io/v1/types.go
The code generator does not support float64 and hence updating
the API to use uint64
> Change the statistics type from float64 to uint64

- main.go
- pkg/cable/wireguard/driver.go
- pkg/util/util.go
- pkg/util/util_test.go
In datastoresyncer, ensureExclusiveEndpoint API when the local endpoints
are compared, they were not matching due to small mismatch in BackendConfig
and this was causing deletion of local endpoint followed by creation of
local endpoint.
Fixes issue: https://github.com/submariner-io/submariner/issues/960
> Avoid deleting local endpoint when Engine pod is restarted

- pkg/cableengine/healthchecker/pinger.go
The pinger is calling onFinish at frequent intervals even
when there is no packet loss. Now the logic is updated to
mark error state for the connection only if there 100% packet
loss
> Fix issue with HealthChecker

- pkg/event/handler.go
- pkg/event/logger/handler.go
- pkg/event/registry.go
- pkg/event/testing/testing.go
- pkg/networkplugin-syncer/handlers/ovn/handler.go
- pkg/networkplugin-syncer/handlers/ovn/infrastructure.go
- pkg/networkplugin-syncer/handlers/ovn/router_ovn_cluster_north.go
- pkg/networkplugin-syncer/handlers/ovn/router_submariner_north.go
- pkg/networkplugin-syncer/main.go
- pkg/routeagent_driver/constants/constants.go
- pkg/routeagent_driver/environment/env.go
- pkg/routeagent_driver/handlers/kubeproxy_iptables/constants.go
- pkg/routeagent_driver/handlers/kubeproxy_iptables/gw_transition.go
- pkg/routeagent_driver/handlers/kubeproxy_iptables/kp_iptables.go
- pkg/routeagent_driver/handlers/kubeproxy_iptables/routes_iface.go
- pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
- pkg/routeagent_driver/handlers/ovn/handler.go
- pkg/routeagent_driver/handlers/ovn/iptables.go
- pkg/routeagent_driver/handlers/ovn/south_rules.go
- pkg/routeagent_driver/handlers/ovn/subnets.go
- pkg/routeagent_driver/main.go
OVN route-agent handler
This handler manages the ip routing rules & routes on the submariner gateway,
as well as the necessary FORWARD iptables.
Extend the generic routeagent handler to the other drivers
This will allow for all those network plugins to be recognized with this same
route agent driver, and at the same time we could make specific modification
if this was ever required.
> Ovn routeagent handler

- pkg/cableengine/healthchecker/pinger.go
When the Timeout value is set in the pinger, it is calcuated from the
time pinger starts and not the time interval between send and receive.
So now we are now using a threshold of packet count after which the connection
will be marked as an error, if the packet loss continues to be 100%.
> Make Healthchecker ping continuous

- pkg/networkplugin-syncer/handlers/ovn/router_ovn_cluster_north.go
- pkg/networkplugin-syncer/handlers/ovn/router_submariner_south.go
This toggles an ACL generated by default in ovn-kubernetes, that allows
traffic from the k8s-host port (a virtual port that exist on each host)
so that fragment ICMP packets will also get back to pods in the gateway nodes.
Without this change, if a packet needs to be fragmented while traversing the
IPSEC tunnel the sender pod won't be properly notified, and the packet will
never be fragmented in the origin, as we use the DNF flag all around
for performance purposes.
> Fix OVNKubernetes PMTU discovery bug

- main.go
- pkg/cableengine/healthchecker/fake/pinger.go
- pkg/cableengine/healthchecker/healthchecker.go
- pkg/cableengine/healthchecker/pinger.go
- pkg/cableengine/syncer/syncer.go
- pkg/cableengine/syncer/syncer_test.go
When the health checker reports a connection error, the gateway syncer sets the gateway connection status to error. When the health checker subsequently reports connected, the gateway syncer needs to set the status back to connected.
The rest of the changes were related to adding unit tests for the health checker's interaction with the gateway syncer. This entailed creating a PingerInterface and a fake implementation that can be hooked into the health checker.
> Reset gateway connection status when health checker reports connected

- .github/workflows/e2e.yml
- .github/workflows/periodic_e2e.yml
The WireGuard module is shipped with the kernel, so wireguard-dkms
hasn't been needed for a little while; the latest point-releases of
Ubuntu drop it entirely, which causes our builds to fail.
> Stop trying to install wireguard-dkms

- tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/ec2-resources.tf
Since the gateway runs on the host network, we need to give access to
its metrics port (8080) if we want Prometheus to be able to scrape its
metrics.
Fixes: #999
> Give access to the gateway metrics port on AWS

- main.go
- pkg/types/types.go
- test/e2e/dataplane/gateway_status.go
- test/e2e/redundancy/gateway_failover.go
Added verification that the GW LatemcyRTT info is present and non-empty for the remote cluster connection. This is coupled with the basic GW status reporting test that was in the redundancy suite and moved to the dataplane suite which seemed more appropriate.
> Add check for GW latency info in E2E

- .github/workflows/e2e.yml
- .github/workflows/periodic_e2e.yml
After the default changed from Strongswan to Libreswan, Libreswan is
being tested twice and strongSwan not at all.
Instead of relying on an implicit default, explicitly list all of the
cable drivers.
> Fix testing Libreswan twice and strongSwan none

- pkg/networkplugin-syncer/handlers/ovn/connection.go
- pkg/networkplugin-syncer/handlers/ovn/handler.go
- pkg/networkplugin-syncer/handlers/ovn/nbctl/nbctl.go
- pkg/networkplugin-syncer/handlers/ovn/nbctl/nbctl_suite_test.go
- pkg/networkplugin-syncer/handlers/ovn/ovn_kubernetes_versions.go
- pkg/networkplugin-syncer/handlers/ovn/router_ovn_cluster_north.go
- pkg/networkplugin-syncer/handlers/ovn/router_submariner_north.go
- pkg/networkplugin-syncer/handlers/ovn/router_submariner_south.go
- pkg/routeagent_driver/handlers/kubeproxy_iptables/iptables_iface.go
- pkg/routeagent_driver/handlers/ovn/constants.go
- pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
- pkg/routeagent_driver/handlers/ovn/handler.go
- pkg/routeagent_driver/iptables/iptables.go
In separate commits:
Avoid src ip masquerade of pods:
Fixes-Issue: #1016
Auto detect submariner-router upstream leg ip
Related-Issue: #994
Expands ovn database address IPs when calling ovn-nbctl  
Fixes-Issue: #1018
Supports new ovn-kubernetes architecture as well as the old one   
Fixes-Issue: #994
> Support latest ovn-kubernetes architecture

- pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
OVN load balancing does not propagate fragment ICMPs down to the
services, so when fragmentation becomes necessary the TCP stack
of the service pod won't be able to detect this situation.
Until this is fixed in OVN this workaround (to be enhanced later)
will fix TCP.
Fixes-Issue: #1022
> Insert MSS clamping for traffic arriving services

- pkg/networkplugin-syncer/handlers/ovn/handler.go
- pkg/networkplugin-syncer/handlers/ovn/nbctl/nbctl.go
- pkg/networkplugin-syncer/handlers/ovn/router_ovn_cluster_north.go
- pkg/networkplugin-syncer/handlers/ovn/router_submariner_south.go
In OVN, you can provide a list of "gateway_chassis" for a router port along
with priorities,  or you can simply attach the router to a chassis.
The former works more reliably in our case. And we don't need the extra features
of "Gateway_Chassis" so this flips the implementation to the router
options field.
> Associate submariner_router to chassis via options

- .github/workflows/upgrade-e2e.yml
The upgrade tests have recently started being frequently canceled by
their 30min job timeouts.
github.com/submariner-io/submariner/actions?query=workflow%3AUpgrade
"The job running on runner GitHub Actions 2 has exceeded the maximum
execution time of 30 minutes."
It seems they are hitting a failure described by #1031 and then being
canceled before they have time to run their post mortem.
> Increase upgrade test timeout 30->45 mins

- .github/workflows/linting.yml
If the repo is dirty after running the validation, fail as it indicates
that the API changed and needs to ge updated.
> Fail codegen "validation" if it caused a change

- pkg/globalnet/controllers/ipam/globalnet.go
- pkg/globalnet/controllers/ipam/ipam.go
Currently, headless services are not supported in Globalnet and are
getting requeued again. Until its supported, lets skip processing them.
> Skip processing headless services in Globalnet

- pkg/globalnet/controllers/ipam/constants.go
- pkg/globalnet/controllers/ipam/ipam.go
Currently, Globalnet works only with kubeproxy iptables driver
and re-uses the IPTable Service Chains created by kubeproxy for
supporting Globalnet ingress use-case for Services.
If there is any issue with kubeproxy or if the cluster uses
kubeproxy with IPVS mode, the IPTable Service Chain will not
be created on the Gateway node and Globalnet continues to
requeue the service waiting for the Chain to be created.
In this PR, we requeue max of 20 times before giving up.
> Limit the number of times a service is requeued

- pkg/networkplugin-syncer/handlers/ovn/connection.go
- pkg/networkplugin-syncer/handlers/ovn/nbctl/nbctl.go
This will enable ovn-kubernetes without SSL, which is the default
mode for kind testing, which also simplifies debuggability.
Depends-On: https://github.com/submariner-io/submariner-operator/pull/1001
> Support non non ssl connections for ovn-kubernetes database

- pkg/globalnet/controllers/ipam/gatewaymonitor.go
- pkg/globalnet/controllers/ipam/globalnet.go
- pkg/globalnet/controllers/ipam/globalnet_ingress.go
- pkg/globalnet/controllers/ipam/ipam.go
- pkg/globalnet/controllers/ipam/node_handler.go
- pkg/globalnet/controllers/ipam/types.go
Currently, Globalnet only supports Pod to remoteService connectivity.
Submariner healthcheck uses ping/icmp to verify the tunnel status to
remoteClusters. In this PR, Globalnet is enhanced to support ping to
the globalIP allocated to the GatewayNodes, so that health-check can
be performed even for Globalnet deployments.
In a subsequent PR, endpoint info will be updated to use globalIPs as
health-check IPs.
Depends On: https://github.com/submariner-io/submariner-operator/pull/1015
Related to: https://github.com/submariner-io/submariner/issues/970
> Globalnet Healthcheck support

- package/Dockerfile.submariner-networkplugin-syncer
To ensure that ovn-nbctl uses the expected schema, explicitly install
the last available package of ovn 20.06 for Fedora 33.
This is a somewhat brittle workaround, the real fix will come in
go-ovn.
Fixes: #1063
> Install ovn 20.06 to match ovn-kubernetes

- pkg/networkplugin-syncer/handlers/ovn/router_submariner_south.go
findChassisByHostname was erroneusly matching cluster-worker with
cluster-worker2 as part of the support for non exact hostnames
(looking for higher level dns names in the hostname at any of
the sides).
Now we first attempt exact host matching, aftewards we try unbalanced
hostnames, but including a dot after the hostname.
Fixes-Issue: #1074
> Fix bug in findChassisByHostname matching

- pkg/cable/driver.go
- pkg/cable/libreswan/libreswan.go
- pkg/cable/strongswan/strongswan.go
- pkg/cable/wireguard/driver.go
- pkg/cableengine/cableengine.go
Previously it returned `[]string` of cable IDs and `InstallCable` used `GetConnections` to find the associated `Connection` instances. So having `GetActiveConnections` return a `[]Connection` simplifies `InstallCable` and also simplifies the libreswan driver - avoiding translation from `Connection` to cable ID then back to `Connection`. It complicates the strongswan driver a bit which now has to do the cable ID to `Connection` but that seems reasonable (plus the strongswan driver is on the chopping block anyway).
> Change GetActiveConnections to return []Connection

- Dockerfile.dapper
- pkg/cableengine/syncer/syncer.go
This includes a prepended patch to pin the shipyard-base-image to release-0.8 version.
(cherry picked from commit fba28a390ad9400280ebe149dcc8dfb11e763afa)
> Fix cable driver in connection latency metric

- main.go
- pkg/controllers/datastoresyncer/datastoresyncer.go
- pkg/controllers/datastoresyncer/node_handler.go
- pkg/globalnet/cleanup/gn_cleanup.go
- pkg/routeagent_driver/constants/constants.go
- pkg/util/util.go
- pkg/util/util_test.go
This PR implements the following changes.
1. When Globalnet is enabled, datastoreSyncer registers for NodeListeners
and will update the localEndpoint with the globalIP of the node.
2. Enables pinger/HealthCheck to work even with Globalnet Deployments.
Depends on: https://github.com/submariner-io/submariner-operator/pull/1019
Fixes Issue: https://github.com/submariner-io/submariner/issues/1068
> Update Endpoint HealthcheckIP to globalIP in Globalnet Deployments

- pkg/networkplugin-syncer/handlers/ovn/connection.go
OVSDB prefixes connections by ssl: and not ssl://
Fixes-Issue: #1088
> Fix SSL detection in OVN connection string

- pkg/cable/libreswan/libreswan.go
This PR enables running pluto process with debug when enabled.
Debugging is controlled via CE_IPSEC_DEBUG env flag. By default
pluto logs are dumped in stdout unless CE_IPSEC_LOGFILE is
explicitly specified.
Fixes issue: https://github.com/submariner-io/submariner/issues/1099
> Support debugging in Libreswan cabledriver

- .github/workflows/linting.yml
- main.go
- package/Dockerfile.submariner-networkplugin-syncer
- pkg/cable/metrics.go
- pkg/cable/wireguard/README.md
- pkg/cable/wireguard/driver.go
- pkg/cable/wireguard/getconnections.go
- pkg/cableengine/cableengine.go
- pkg/controllers/datastoresyncer/datastoresyncer.go
- pkg/controllers/datastoresyncer/node_handler.go
- pkg/globalnet/cleanup/gn_cleanup.go
- pkg/globalnet/controllers/ipam/gatewaymonitor.go
- pkg/globalnet/controllers/ipam/globalnet.go
- pkg/globalnet/controllers/ipam/globalnet_ingress.go
- pkg/globalnet/controllers/ipam/ipam.go
- pkg/globalnet/controllers/ipam/node_handler.go
- pkg/globalnet/controllers/ipam/types.go
- pkg/networkplugin-syncer/handlers/ovn/connection.go
- pkg/networkplugin-syncer/handlers/ovn/nbctl/nbctl.go
- pkg/networkplugin-syncer/handlers/ovn/router_submariner_south.go
- pkg/routeagent_driver/constants/constants.go
- pkg/util/util.go
- pkg/util/util_test.go
Includes the following patches:
7f481f7 Fix SSL detection in OVN connection string
92dc605 Use the PR base branch as reference when linting
ec721f5 Update Endpoint HealthcheckIP to globalIP in Globalnet Deployments
10adc6d Don't try to remove local cable
c126c22 Fix bug in findChassisByHostname matching
d255f6a Install ovn 20.06 to match ovn-kubernetes
78b9b8a Globalnet Healthcheck support
30aac0f Adding wireguard prometheus metrics
73ce104 Support non non ssl connections for ovn-kubernetes database
> Release 0.8 backports

- pkg/networkplugin-syncer/handlers/ovn/connection.go
This is flagged by gosec: tls.Config should specify the minimum TLS
version, which should be 1.2.
> Specify the minimum TLS version for OVN

- .github/workflows/release.yml
Pass RELEASE_ARGS on the call, since GITHUB_REF set in the `env`
directive doesn't get properly expanded.
> Pass RELEASE_ARGS on the command call

- package/Dockerfile.submariner-gateway
- package/iptables-wrapper-installer.sh
- package/submariner.sh
... instead of our own. This ensures that our container images use the
correct iptables implementation without placing any particular
requirements on the host. It also removes the requirement for mounting
the host file system in the container (which appears to be restricted
in OpenShift 4.7 and later).
This requires installing both variants of iptables in the container;
we can do that on Fedora, but not on UBI8, so this is limited to the
gateway image for the time being.
See https://github.com/kubernetes-sigs/iptables-wrappers for details.
> Use the K8s SIG iptables wrapper
