submariner-io/submariner

pkg/controllers/datastoresyncer/datastoresyncer.go

- There were several call sites that did not check the error return value.
Either propagate the error or at least log it.
- There were several calls to panic in cases where an update operation failed.
It seems a bit harsh to terminate in this case and is inconsistent with the
handling of other failed CRUD operations (which previously ignored errors).
For consistency, CRUD failures now return and propagate the error.
- Added format args to some log messages to provide more context
- Modified the wording in some log messages for consistency

Improve error handling/reporting in DatastoreSyncer

---

pkg/datastore/kubernetes/kubernetes.go

As the TODO comment indicates, this function is O(n^2).
Uses a map to make it O(n).

Optimize kubernetes.stringSliceOverlaps

---

pkg/datastore/phpapi/phpapi.go

On results from http, the body should be closed only if there was no
error. This patch moves all deferred closures after the error checks,
and adds a missing error check.

Check for errors before deferring body closure

---

main.go
pkg/cableengine/ipsec/ipsec.go
pkg/datastore/phpapi/phpapi.go

This groups a number of cleanups requested by `golint`.

golint cleanups

---

pkg/routeagent/controllers/route/route.go

- There were several call sites that did not check the error return value.
Either propagate the error or at least log it.
- The cleanXfrmPolicies and cleanRoutes functions return error but the callers do not
check the error. It seems an error is not catastrophic to the callers so
they do not need to handle it. Also each function has a loop in which an error could
occur but the current behavior ignores it and continues. If we return the error then
subsequent iterations of the loop would be elided. It seems it's safest to keep the
current behavior but log the error. Also there doesn't seem to be any reason to
return an error so that was removed
- Added format args to some log messages to provide more context
- Modified the wording in some log messages for consistency
Signed-off-by: Tom …

Improve error handling/reporting in route.go

---

main.go
pkg/util/util.go

- There was one call site that did not check the error return value.
- Ensure Fatalf call sites properly log the error.
- Modified util.GetLocalEndpoint to propagate errors to let main handle it.
- Changed some local var names to improved readability (eg ds -> databroker).

Modifications to main.go

---

main.go
pkg/cableengine/ipsec/ipsec.go
pkg/controllers/datastoresyncer/datastoresyncer.go
pkg/datastore/datastore.go
pkg/datastore/kubernetes/kubernetes.go
pkg/datastore/phpapi/phpapi.go
pkg/routeagent/controllers/route/route.go
pkg/routeagent/main.go
pkg/types/types.go
pkg/util/util.go

golint corrections for all files in pkg folder
Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

Golint corrections for pkg

---

pkg/datastore/kubernetes/kubernetes.go

NewK8sDatastore exports an unexported type, which makes it hard to
use. This patch renames the datastore types to Datastore and
DatastoreSpecification respectively, exporting them and making their
name match their use.

Export the datastore types

---

main.go
pkg/datastore/kubernetes/kubernetes.go

- Rename to NewDatastore to to avoid stuttering
- Return error instead of calling Fatalf
- Move instantiation of Datastore to the end return

Refactor NewK8sDatastore function

---

.gitignore

... in the same way as submariner-engine.

Ignore submariner-route-agent

---

.travis.yml
Dockerfile.dapper
README.md
scripts/e2e
scripts/kind-e2e/cluster1-config.yaml
scripts/kind-e2e/cluster2-config.yaml
scripts/kind-e2e/cluster3-config.yaml
scripts/kind-e2e/e2e.sh
scripts/kind-e2e/netshoot.yaml
scripts/kind-e2e/nginx-demo.yaml

1. Add support for e2e tests with kind. make e2e command
2. Add support for running go test.

Simple e2e testing with kind

---

README.md
scripts/test
test/e2e/dataplane/tcp_pod_to_service.go
test/e2e/e2e.go
test/e2e/e2e_test.go
test/e2e/example/example.go
test/e2e/framework/api_errors.go
test/e2e/framework/cleanup.go
test/e2e/framework/framework.go
test/e2e/framework/logging.go
test/e2e/framework/network_pods.go
test/e2e/framework/pods.go
test/e2e/framework/services.go
test/e2e/framework/test_context.go
test/e2e/framework/util.go

The framework is based on the work done in kubefed and kubernetes around E2E, and it's based in ginkgo.

Basic framework for E2E testing of submariner, including one example

---

test/e2e/dataplane/tcp_pod_to_service.go
test/e2e/e2e_test.go
test/e2e/example/example.go
test/e2e/framework/api_errors.go
test/e2e/framework/framework.go
test/e2e/framework/logging.go
test/e2e/framework/network_pods.go
test/e2e/framework/pods.go
test/e2e/framework/services.go
test/e2e/framework/test_context.go
test/e2e/framework/util.go

Format tests using goimports

---

pkg/controllers/tunnel/tunnel.go

- Handle all returned errors as flagged by golangci-lint
- Propagate errors from functions that return error
- Ensure all error objects are logged

Cleanup error handling in tunnel

---

Makefile

Declare all script targets as phony

---

pkg/routeagent/controllers/route/route_test.go

Added unit tests for 2 functions in route.go
This is an update to Janki's original patch here:
https://github.com/rancher/submariner/pull/44
Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

UT for route pkg

---

scripts/kind-e2e/e2e.sh
test/e2e/framework/ginkgowrapper/wrapper.go
test/e2e/framework/logging.go
test/e2e/framework/network_pods.go

This makes the e2e tests from test/e2e directory run when you execute make e2e

Execute the in-tree e2e go tests

---

scripts/kind-e2e/e2e.sh

Fix issue with ginkgo between consecutive runs:
In order to **make e2e status=keep** to be executed successfully multiple times in a row, the kubeconfig for e2e tests must be read from shared persistent output directory and not from ephemeral build container, as the build container is discarded every run.
Remove hard coded directory locations:
Auto calculate directory structure based on git command and remove all the hard coded values.

Fix for ginkgo e2e recurring runs

---

scripts/codegen

Add script to run the k8s code generator

---

Dockerfile.dapper
Makefile
scripts/kind-e2e/README.md
scripts/kind-e2e/e2e.sh
scripts/kind-e2e/nginx-federated.sh

This PR is adding kubefed=true command to E2E flow.

Add kubefed installation to E2E flow as an option

---

main.go

close https://github.com/rancher/submariner/issues/12 
Use current namespace
test with [negash/submariner:v0.0.1](https://hub.docker.com/r/negash/submariner/tags)

Update main.go to use current namespace

---

pkg/cableengine/ipsec/ipsec.go

Delete an unused constant

---

Dockerfile.dapper

This helps with ongoing dependency maintenance.

Document Dapper Dockerfile requirements

---

scripts/kind-e2e/README.md

"cleanup" needs to be replaced with "clean"
Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

Correct cleanup command

---

scripts/kind-e2e/e2e.sh

This greatly reduces e2e deployment time.

Deploy kind clusters in parallel

---

.travis.yml
pkg/cableengine/ipsec/strongswan.go

Run validation and tests on Travis

---

README.md

Add badges for travis and godoc.org

Add travis and godoc badges to the README.md

---

scripts/kind-e2e/e2e.sh

This changes the e2e script to always specify the kube context, to
avoid interactions with other uses of use-context, and allow future
parallelisation of context-sensitive steps.

Always specify the context

---

scripts/kind-e2e/e2e.sh

This will have to be rebased once #109 is merged.

Parallel Helm

---

.travis.yml

Check if scripts/kind-e2e/e2e.sh was changed, if yes it will run again the e2e flow on existing infrastructure.

Test recurring run if e2e.sh changes

---

.travis.yml
scripts/ci
scripts/e2e
scripts/kind-e2e/e2e.sh
scripts/lib/debug_functions

Using bash 'trap DEBUG' to print relevant commands before execution

Adding verbosity to e2e.sh

---

scripts/kind-e2e/e2e.sh

These commits fix a couple of minor problems in `e2e.sh`.

Minor e2e fixes

---

tools/openshift/ocp-ipi-aws/README.md
tools/openshift/ocp-ipi-aws/main.tf
tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/ec2-resources.tf
tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/machine-set-resources.tf
tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/outputs.tf
tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/templates/machine-set.yaml
tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/variables.tf
tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/vpc-resources.tf
tools/openshift/ocp-ipi-aws/outputs.tf
tools/openshift/ocp-ipi-aws/prep_for_subm.sh

This set of script + terraform code will help administrators update their
AWS resources to host the submariner gateway worker node which require
an external IP.

openshift-installer aws provisioned infra tool

---

scripts/kind-e2e/e2e.sh
scripts/package
scripts/release

Use the quay.io repo everywhere instead of rancher

---

Dockerfile.dapper
package/Dockerfile.dapper-base

This needs #130 and an image setup in Quay before it can be merged.

Pull Dapper base image from Quay

---

test/e2e/dataplane/tcp_pod_to_service.go

Specify cluster for listener and connector pods
in pod to service connectivity tests.
Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>

Add clustername to TestPod2ServiceTCP

---

scripts/kind-e2e/e2e.sh

Minor refactor adding `helm_install_subm` helper function

e2s: helm install subm helper func

---

scripts/kind-e2e/README.md
scripts/kind-e2e/e2e.sh

Remove unneeded ci option when performing clean up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner/226)

E2E read me update

---

scripts/kind-e2e/e2e.sh
test/e2e/dataplane/tcp_pod_connectivity.go
test/e2e/e2e_test.go
test/e2e/framework/framework.go
test/e2e/framework/network_pods.go
test/e2e/framework/pods.go
test/e2e/redundancy/gateway_failover.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner/204)

Gateway redundancy E2E tests

---

test/e2e/framework/services.go

If you try to run a second service connectivity test in a spec it will
fail due to the service already existing. Modified CreateTCPService so if
it fails with IsAlreadyExists error, delete the service and try again.

E2E: delete service if already exists

---

test/e2e/framework/framework.go
test/e2e/framework/network_pods.go
test/e2e/framework/submariner_resources.go
test/e2e/redundancy/gateway_failover.go

Two gateway nodes configured with 1 submariner engine replica.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/submariner-io/submariner/218)

Add second E2E gateway failover scenario

---

scripts/kind-e2e/e2e.sh
test/e2e/cluster/add_remove_cluster.go
test/e2e/dataplane/tcp_pod_connectivity.go
test/e2e/e2e_test.go
test/e2e/framework/network_pods.go
test/e2e/framework/services.go

This defines a test scenario where a new
cluster is added to an existing setup
and connectivity between pods in the new and
existing cluster is tested.
Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>

Test for cluster add remove scenario

---

docs/contributing.md

Add SubM weekly meeting info to Contributing docs

---

README.md

Add subctl installation instructions

---

README.md

Update subctl install docs for 0.0.3 release

---

pkg/globalnet/controllers/ipam/ippool.go
pkg/globalnet/controllers/ipam/ippool_test.go

Unit Tests for ipam/ippool

---

pkg/globalnet/controllers/ipam/ippool_test.go

The IpPool.IsFull function was recently removed but is referenced in unit tests which was merged afterwards.

Fix build error due to missing IsFull

---

pkg/cableengine/ipsec/strongswan.go

A recent change in strongswan modified the default vici socket path,
making submariner-engine unable to find the vici interface socket.
This patch explicitly specifies the vici socket path in charon.conf
and fixes the issue.
Fixes: #288

Fixes strongswan vici socket path

---

pkg/globalnet/controllers/ipam/ippool_test.go

- use BeforeEach instead of shared vars
- improve test context messages

Refactor IpPool tests

---

scripts/kind-e2e/e2e.sh
scripts/kind-e2e/lib_helm_deploy_subm.sh
scripts/kind-e2e/lib_operator_deploy_subm.sh

Cleanup e2e script, separate subctl/helm logic

---

scripts/kind-e2e/e2e.sh
scripts/kind-e2e/lib_helm_deploy_subm.sh
scripts/kind-e2e/lib_operator_deploy_subm.sh

Refactor vars in e2e script/libs

---

pkg/routeagent/controllers/route/route.go

Currently the MTU on Submariner VXLAN interface is hardcoded to 1450.
In some of the environments Jumbo frames are used. So, ideally
Submariner should identify the outgoing interface and configure
the appropriate MTU. This patch fixes it.
Fixes Issue: https://github.com/submariner-io/submariner/issues/301

Fix MTU on vx-submariner interface

---

package/Dockerfile.dapper-base
scripts/kind-e2e/lib_operator_deploy_subm.sh

This queries the GitHub API to find the latest subctl release, and
downloads that.

Download the latest subctl

---

pkg/routeagent/controllers/route/route.go

Call Forget on all code paths in route.go

---

pkg/routeagent/controllers/route/route.go

HA Failover tests start working flawlesly after this change, otherwise
sometimes the node that previously was a master gw, left over the 220
routing table, causing conflict with the default routes managed by
the route agent.
Fixes: #346

Cleanup strongswan table 220 when master gw becomes non-master.

---

.travis.yml

Test e2e cleanup at the end of successful CI runs

---

main.go
pkg/cableengine/ipsec/ipsec.go
pkg/cableengine/ipsec/strongswan.go
pkg/controllers/datastoresyncer/datastoresyncer.go
pkg/controllers/tunnel/tunnel.go
pkg/datastore/kubernetes/kubernetes.go
pkg/datastore/phpapi/phpapi.go
pkg/util/util.go

This is a series of commits to enhance logging in the various engine components, one commit per Go file.  In general the changes encompass:
-  Use log.DEBUG approriately
-  Enhance log messages and formatting
-  Renamed some local vars to enhance clarity

Refactor engine logging

---

.travis.yml

(cherry picked from commit c5c1495efa5cca73c08135e897551b1ca86d98e4)

Start building stable branches

---

package/submariner-route-agent.sh
pkg/apis/submariner.io/v1/string.go
pkg/apis/submariner.io/v1/string_test.go
pkg/routeagent/controllers/route/driver.go
pkg/routeagent/controllers/route/iptables.go
pkg/routeagent/controllers/route/route.go
pkg/routeagent/controllers/route/vxlan.go

This cleans up logging on the route-agent and fixes some of the issues seen, logging them and failing more gracefully. 
Related-Issue: #341

Route agent logs refactor

---

pkg/datastore/datastore.go
pkg/datastore/fake/datastore.go
pkg/datastore/kubernetes/kubernetes.go
pkg/datastore/phpapi/phpapi.go

...for use in upcoming unit tests

Add fake Datastore implementation

---

pkg/globalnet/controllers/ipam/gatewaymonitor.go
pkg/globalnet/controllers/ipam/globalnet.go
pkg/globalnet/controllers/ipam/globalnet_egress.go
pkg/globalnet/controllers/ipam/globalnet_ingress.go
pkg/globalnet/controllers/ipam/ipam.go
pkg/globalnet/main.go
pkg/routeagent/main.go

Use DEBUG/TRACE levels in globalnet

---

test/e2e/framework/framework.go

The same namespace is being added to namespacesToDelete
multiple times and thus is attempted to be deleted
multiple times. This is relatively benign save for a message
printed multiple times but we should prevent it. Change
namespacesToDelete to a map.
Also enhanced some output messages.

De-duplicate namespacesToDelete in E2E Framework

---

test/e2e/framework/framework.go

K8s has an aggregate error utility - use that for compiling
and reporting multiple errors to simplify.

Use aggregate error in Framework.AfterEach

---

.travis.yml

Test re-deploying on an already-deployed environment when any deployment
script is modified, not just e2e.sh.
Closes: #392

Test re-deploy if any deploy scripts change

---

scripts/dapper-image

Our scripts had an error and didn't detect dapper image changes on
a master merge.
Fixes: #438

Builds the dapper image when a PR is merged to master

---

scripts/kind-e2e/e2e.sh
scripts/kind-e2e/lib_helm_deploy_subm.sh
scripts/kind-e2e/lib_operator_deploy_subm.sh
scripts/lib/debug_functions

This is a proposal for improving the BASH based deployment to make it more maintainable and easy to extend.

Better bash - refactoring

---

package/Dockerfile.dapper-base
test/e2e/e2e.go
test/e2e/e2e_test.go
test/e2e/framework/test_context.go

This requires upgrading to golangci-lint 1.18 to fix
https://github.com/golangci/golangci-lint/issues/658 with Go 1.13.

Upgrade to Fedora 31

---

Makefile
scripts/kind-e2e/e2e.sh

The shflags library is now available in the shipyard base image, so use
that for the flag parsing of e2e.sh

Use shflags for command line flag parsing

---

docs/testing.md
scripts/kind-e2e/README.md

A few minor remnants remained after #484 

Remove remaining kubefed references

---

pkg/cable/status.go
pkg/cableengine/cableengine.go

Define the status structures for a connection list

---

pkg/cable/driver.go
pkg/cable/ipsec/getconnections.go
pkg/cable/ipsec/getconnections_test.go
pkg/cable/ipsec/ipsec_suite_test.go
pkg/cable/ipsec/strongswan.go
pkg/cable/ipsec/strongswan_test.go
pkg/cable/status.go
pkg/cable/wireguard/getconnections.go
pkg/cableengine/cableengine.go

Implement GetConnections on the cable engine.

---

Makefile
scripts/kind-e2e/README.md
scripts/reload-images

```
make reload-images restart=gateway
```
restart variable can be all, gateway, routeagent, globalnet or none
and defaults to all

Restart pods when reloading images

---

pkg/apis/submariner.io/v1/types.go
pkg/cableengine/syncer/syncer.go
test/e2e/framework/framework.go
test/e2e/redundancy/gateway_failover.go

Update redundancy e2e tests with improvements from code review

---

docs/contributing.md

This updates the build instructions and the Slack channel.

Update the contributing guide

---

.travis.yml

Since it was changed to a boolean flag, no need to send true/false

Globalnet flag adjustment

---

Dockerfile.dapper
pkg/cable/wireguard/README.md
pkg/cable/wireguard/driver.go
pkg/cable/wireguard/getconnections.go

Implement GetConnections
Update README.md --install linux-headers

add Wireguard support for connection status

---

.github/workflows/e2e.yaml

Adding a workflow to run the E2E tests in GitHub Actions.
Closes #547

Add GitHub Actions E2E tests

---

pkg/cable/libreswan/libreswan.go

The identifier needs to match the expected authentication, rather than
the apparent IP address, so set it explicitly to the private address.
NAT on AWS at least also needs encapsulation, which doesn’t get
automatically set up, so enforce it when NAT is requested.

Libreswan: add explicit authentication and encaps

---

go.mod
go.sum
pkg/globalnet/controllers/ipam/gatewaymonitor.go
pkg/globalnet/controllers/ipam/globalnet.go
pkg/globalnet/controllers/ipam/globalnet_ingress.go
pkg/globalnet/controllers/ipam/ipam.go

This PR reorganizes the code slightly and includes additional
logging which will assist whenever there is any failure in GN
jobs.
Partially fixes: https://github.com/submariner-io/submariner/issues/596

Fix random CI failures in globanet jobs

---

.github/workflows/e2e.yaml
Makefile
docs/testing.md

Added a flag that can be sent to make to pass additional options, e.g
`using="globalnet, wireguard, helm"`

Add `using=` make flag

---

pkg/datastore/kubernetes/kubernetes.go

The trust anchor stored in the broker information reflects the trust
chain of the token, not necessarily the trust chain of the API
endpoint; but we're using it for the latter in all cases.
This changes NewDatastore to check whether the clientset can be used,
by retrieving the endpoints. This allows the configuration to be
verified, and switched to use the stored trust anchor if necessary.
Fixes: #649

Check whether the CA trust chain is needed

---

scripts/reload-images

Fix error with reload-images target

---

pkg/cable/driver.go

... when an unknown type is specified.

List the supported cable driver types

---

pkg/cable/wireguard/driver.go

Remove routing (now in RouteAgent per #656)
Change interface name to be `submariner`. Should consider making this user configurable.
WireGuard driver now assumes that RouteAgent adds routes to CIDRs in remote clusters which are forwarded to `submariner` interface. The driver only adds those CIDRs to `allowed-IPs`. RouteAgent is also expected to flush the routes if the Gateway moves to another node. The `submariner` interface is still created by the driver on startup. Any existing interface is first removed, so any existing routes would be removed too.

Remove routing from WireGuard cable driver

---

CODEOWNERS

Related-Issue: https://github.com/submariner-io/submariner/issues/662

Add skitt permissiosn to CODEOWNERS

---

.golangci.yml
pkg/routeagent/controllers/route/driver.go
pkg/routeagent/controllers/route/route.go

Enable gosec linting

---

.golangci.yml
main.go

... and reduce the interfaces it flagged.

Enable interfacer linting

---

.golangci.yml
pkg/apis/submariner.io/v1/string.go
pkg/cable/libreswan/libreswan.go
pkg/cable/strongswan/getconnections.go
pkg/cable/strongswan/strongswan.go
pkg/cable/strongswan/strongswan_test.go
pkg/cableengine/cableengine.go
pkg/cableengine/syncer/syncer.go
pkg/controllers/datastoresyncer/datastoresyncer.go
pkg/datastore/kubernetes/kubernetes.go
pkg/globalnet/controllers/ipam/ipam.go
pkg/routeagent/controllers/route/route.go
pkg/routeagent/controllers/route/vxlan.go
test/e2e/framework/framework.go

Enable whitespace golangci-lint linter, fix errors

---

.golangci.yml
pkg/cable/driver.go
pkg/cable/libreswan/libreswan.go

Based on https://github.com/submariner-io/submariner/pull/698

Enable misspell linter, fix existing errors

---

go.mod
main.go
pkg/cableengine/fake/cableengine.go
pkg/controllers/tunnel/tunnel.go
pkg/controllers/tunnel/tunnel_test.go

Preceded by some minor cleanup commits to simplify the tests.

Add tunnel controller tests

---

go.mod
go.sum

Update shipyard version in go.mod

---

.golangci.yml
pkg/cableengine/syncer/syncer.go

Enable unparam unused param linting, fix error

---

Dockerfile.dapper
go.mod
go.sum

Update to 0.5.0

---

pkg/routeagent/controllers/route/route.go

During some recent refactoring, it looks like the code that updates
the remoteVteps is moved under cniIface validation. This PR fixes it.

Remote vteps to be populated even when CNIIface is missing

---

pkg/routeagent/controllers/route/route.go

On AWS Clusters, it was seen that nodes are named with FQDN
(i.e., hostname.domainname). However, on many of the other
K8s clusters we tested so far (like KIND, OSP etc), the
hostnames were matching with the nodeNames.
In order to support connectivity from HostNetwork to
remoteClusters (when using Globalnet), routeagent Pod
annotates the respective nodes with the cniIfaceIP
annotation. In the current code, where this annotation
is added, we were using the hostname to query the node
info. This was failing on AWS Clusters for the issue
mentioned above. This PR fixes it.
Fixes issue: https://github.com/submariner-io/submariner/issues/736

AWS: Fix missing cniIfaceIP annotation for Node

---

pkg/globalnet/main.go

During the Submariner installation phase (aka when join command is issued),
typically all the Submariner pods would be initialized in parallel.
Submariner-gateway Pod, being one of them, is responsible for creating the
clusterCRD and the creation of this CRD would normally take a few seconds.
In the meantime, if GlobalnetPod tries to read the clusterCRD and finds it
missing, it should retry the operation few times before giving up. This PR
implements this change.
Fixes issue: https://github.com/submariner-io/submariner/issues/726

During initialization, if clusterCRD is missing, retry few times

---

CODEOWNERS

Fix path in codeowners file

---

pkg/routeagent/controllers/route/route.go

Currently, while routeagent is running, it queries the list of
other routeagent pods in the cluster to get their ip-addresses.
This info is necessary while creating the VxLAN tunnels in the
cluster. In one of the clusters, it was seen that when routeagent
pods are queried, the pod.Status.PodIP was empty. The empty check
was not handled in the code and this was leading the routeagent
pod not coming up on the Gateway node. This PR fixes it.
Fixes issue: https://github.com/submariner-io/submariner/issues/749

Fix error in routeagent-pod while configuring vxLan tunnels

---

.github/stale.yml
.github/workflows/dco-check.yml
.github/workflows/e2e.yml
.github/workflows/gitlint.yml
.github/workflows/md-links-periodic.yml
.github/workflows/md-links.yml
.github/workflows/release.yml
.github/workflows/validation.yml
.github/workflows/yaml-lint.yml
.golangci.yml
.markdownlint.yml
.yamllint.yml
tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/templates/machine-set.yaml

Add YAML linting, fix errors

---

.github/workflows/periodic.yml

This syntax error causes the job to fail.

Fix typo in periodic job

---

.github/workflows/e2e.yml
.github/workflows/linting.yml
.github/workflows/periodic.yml
.github/workflows/release.yml
.github/workflows/unit.yml

Clean up names of GHA Steps/Jobs

---

pkg/cable/libreswan/libreswan.go
pkg/cableengine/syncer/syncer.go
test/e2e/framework/framework.go

For https://github.com/submariner-io/submariner-operator/issues/719.

Add debug output in libreswan driver

---

.github/stale.yml

Signed-off-by: nyechiel <n.yechiel@gmail.com>

Update stale bot inactivity to 60 days

---

go.sum

Tidy up go.sum

---

tools/openshift/ocp-ipi-aws/prep_for_subm.sh

- Fix https://github.com/submariner-io/submariner/issues/241
- Fix download_ocp_ipi_aws_tool()
- Fix several variables assignments
Signed-off-by: Noam Manos <nmanos@redhat.com>

Fixes for prep_for_subm.sh

---

pkg/cable/libreswan/libreswan.go

Occasionally, with libreswan driver, we see that Connection status
for remote clusters in Gateway object shows as connecting eventhough
the datapath continues to work fine. In Libreswan driver, Gateway status
is populated by quering the IPsec SAs from the host and validating the
connection names.
On debugging this issue, it was seen that the connections are all
loaded but some of them were in "prospective erouted" state and not yet
active. In this PR, instead of checking for all the connections associated
to a remote cluster, we just check if atleast one of the connections is
established and mark the tunnel status accordingly.
Fixes issue: https://github.com/submariner-io/submariner-operator/issues/719

Fix Gateway connection status for Libreswan cable driver

---

tools/openshift/ocp-ipi-aws/README.md
tools/openshift/ocp-ipi-aws/main.tf
tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/ec2-resources.tf
tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/machine-set-resources.tf
tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/templates/machine-set.yaml
tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/variables.tf
tools/openshift/ocp-ipi-aws/prep_for_subm.sh

now accepts the following environment variables:
- IPSEC_NATT_PORT
- IPSEC_IKE_PORT
- GW_INSTANCE_TYPE
Fixes-Issue: #240
Co-Authored-By: Noam Manos <nmanos@redhat.com>

Parameters for prep script

---

pkg/routeagent/controllers/route/route.go

Convert route controller to use workqueue abstraction

---

tools/openshift/ocp-ipi-aws/README.md

Fix readme to include oc utility

---

Makefile
package/Dockerfile.submariner-networkplugin-syncer
package/submariner-networkplugin-syncer.sh
pkg/networkplugin-syncer/main.go

This is a stub to build the network syncer later on top.

Hollow networkplugin syncer

---

test/e2e/redundancy/gateway_failover.go

Intermittent failures have been seen during GW cleanup for the engine pod restart test. After deleting the engine pod, we intend to wait for a new pod to spin up but sometimes the previous one hasn't gone away yet so the check prematurely succeeds. On cleanup, we may happen to observe the new pod in the temporary passive state and unintentionally un-label it
thus causing subsequent failures.

Fix intermittent E2E GW redundancy failures

---

go.mod
go.sum
main.go
pkg/controllers/datastoresyncer/datastore_cluster_sync_test.go
pkg/controllers/datastoresyncer/datastore_endpoint_sync_test.go
pkg/controllers/datastoresyncer/datastoresyncer.go
pkg/controllers/datastoresyncer/datastoresyncer_suite_test.go
pkg/controllers/tunnel/tunnel.go

Convert datastoresyncer to use admiral broker syncer

---

pkg/event/event_suite_test.go
pkg/event/registry_test.go

Modifications to event registry tests

---

.markdownlint.yml
CODE-OF-CONDUCT.md
CONTRIBUTING.md
README.md

See commit messages for details.

Remove unnecessary MD lint ignores, clean up H1 headings

---

pkg/cable/metrics.go

Add a shared metrics infrastructure for rx/tx bytes

---

.github/workflows/periodic_e2e.yml
.github/workflows/periodic_linting.yml

See commit messages for details.

Add periodic E2E tests to find flaky failures

---

go.mod
go.sum

Fix invalid admiral version in go.mod

---

pkg/globalnet/controllers/ipam/gatewaymonitor.go
pkg/globalnet/controllers/ipam/types.go

Fixes issue: https://github.com/submariner-io/submariner/issues/929

Flush Globalnet chains when Globalnet Pod is terminated

---

tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/ec2-resources.tf

Recently Submariner pods are configured as infrastructure pods
which will ignore any taints. Because of this change, they will
get scheduled even on the Master nodes. To validate this use-case
Submariner e2e test pods are also modified to tolerate any taints.
So, we should open UDP/4800 ports between the master and worker
nodes in an AWS cluster. This PR handles this change in terraform
scripts.

Open UDP/4800 ports between master and worker nodes on AWS

---

tools/openshift/ocp-ipi-aws/README.md

Signed-off-by: nyechiel <nyechiel@redhat.com>

Update OCP IPI README

---

go.mod
go.sum
main.go
pkg/cableengine/healthchecker/healthchecker.go
pkg/cableengine/healthchecker/healthchecker_suite_test.go
pkg/cableengine/healthchecker/pinger.go
pkg/cableengine/healthchecker/statistics.go
pkg/cableengine/healthchecker/statistics_test.go
pkg/cableengine/syncer/syncer.go
pkg/cableengine/syncer/syncer_test.go
pkg/util/util.go
pkg/util/util_test.go

*Populate the healthchecker Ip
*Ping the healthchecker IP to check the remote
gateway status
*Update the gateway satus if the ping fails
Fixes: submariner-io/submariner#821

Add health checker implementation

---

pkg/routeagent_driver/constants/constants.go
pkg/routeagent_driver/handlers/kubeproxy_iptables/constants.go

Move constant comments with constant

---

pkg/apis/submariner.io/v1/types.go

Add units in healthcheck fields

---

.github/workflows/release.yml

Release networkplugin-syncer image

---

pkg/cable/metrics.go
pkg/cableengine/syncer/syncer.go

Record connection latency metric

---

main.go
pkg/cableengine/healthchecker/healthchecker.go
pkg/cableengine/healthchecker/pinger.go
pkg/cableengine/syncer/syncer_test.go
pkg/types/types.go

Use health check config values

---

pkg/cableengine/healthchecker/pinger.go
pkg/cableengine/healthchecker/pinger_test.go

See the individual [commits](https://github.com/submariner-io/submariner/pull/982/commits) for detail.

Modifications to the health check pinger

---

tools/openshift/ocp-ipi-aws/README.md

Document the use of port 8080 in the OCS-IPI README

---

CODEOWNERS
CODEOWNERS.in

Update CODEOWNERS file to use routeagent_driver

---

pkg/routeagent_driver/constants/constants.go
pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
pkg/routeagent_driver/handlers/ovn/handler.go
pkg/routeagent_driver/handlers/ovn/host_networking.go
pkg/routeagent_driver/handlers/ovn/south_rules.go

This PR implements Host network to remote pod/service support
in OVN route-agent driver.
Fixes issue: https://github.com/submariner-io/submariner/issues/993
Co-Authored-By: Miguel Angel Ajo <majopela@redhat.com>

OVN: Host-network to remote pod/service support

---

pkg/networkplugin-syncer/handlers/ovn/nbctl/nbctl.go
pkg/networkplugin-syncer/handlers/ovn/router_submariner_south.go
pkg/networkplugin-syncer/handlers/ovn/services.go

Assign ovn k8s loadbalancers to submariner_router

---

go.sum

Tidy up for release

---

pkg/controllers/datastoresyncer/datastore_0.8.0_upgrade_test.go
pkg/controllers/datastoresyncer/datastoresyncer.go
test/e2e/framework/submariner_resources.go
test/e2e/redundancy/gateway_failover.go

Fix 0.8.0 upgrade issue

---

pkg/cableengine/healthchecker/pinger.go

The healthchecker use the same pinger even if the ping fails.
This is leading into stale conntrack entries, which causes pakcet
loss even if the connection is established. So in the event of
a failure a new pinger will be created.
Fixes: #996

Resetting the pinger after connection error

---

pkg/cableengine/cableengine.go

Instead of waiting for a delete notification for an endpoint,
if add/update notification is received, delete the old connection
and restablish with the new parameters.
Related to: https://github.com/submariner-io/submariner/issues/1036

Establish connection to remoteEndpoints upon notification

---

.github/workflows/linting.yml
.legal.json
pkg/globalnet/controllers/ipam/node_handler.go

Add a license header check

---

pkg/globalnet/main.go

Since the globalnet collects it's own metrics,
they need to be exposed separately from the engine
Related issue #890

Expose prometheus metrics for globalnet

---

pkg/globalnet/controllers/ipam/globalnet.go
pkg/globalnet/controllers/ipam/globalnet_ingress.go

Fixes https://github.com/submariner-io/submariner/issues/1091.

Handle empty port name in kubeProxyClusterIpServiceChainName

---

go.mod
go.sum
main.go
pkg/cableengine/healthchecker/healthchecker.go
pkg/controllers/datastoresyncer/datastoresyncer.go
pkg/controllers/datastoresyncer/datastoresyncer_suite_test.go
pkg/controllers/datastoresyncer/node_handler.go
pkg/controllers/tunnel/tunnel.go
pkg/event/controller/endpoint_created.go
pkg/event/controller/endpoint_removed.go
pkg/event/controller/endpoint_updated.go
pkg/event/controller/node_handlers.go

The addition of the `numRequeues` param to callback functions and changes to broker syncer creation.

Adopt admiral API changes

---

package/Dockerfile.submariner-globalnet
package/Dockerfile.submariner-route-agent

... so we can build ARM images.
This needs https://github.com/submariner-io/submariner/pull/964

Switch to Fedora for all images

---

.github/workflows/e2e.yml
Makefile
scripts/cluster_settings.ovn

* Enable OVN in Makefile
* Add OVN jobs to e2e
Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

Enable OVN CNI

---

.github/workflows/e2e.yml
.github/workflows/flake_finder.yml
.github/workflows/release.yml
.github/workflows/upgrade-e2e.yml

As we added new composite actions, use them.

Use shared GHA from Shipyard

---

package/Dockerfile.submariner-globalnet
package/Dockerfile.submariner-route-agent

... it doesn’t matter if we drop support for ARM32.
This reverts commit 8545dcc96ec9d4551b2ac67e6866178927ad1407.

Switch back to UBI where possible

---

.golangci.yml
pkg/globalnet/controllers/ipam/gatewaymonitor_test.go

Enable goconst Go linter
Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

Enable goconst Go linters

---

test/e2e/redundancy/route_agent_restart.go

Closes https://github.com/submariner-io/submariner/issues/825

Add E2E route agent restart tests
